### ISSUE TITLE
"Run test under cursor" fails with python error

### ISSUE THREAD

**Issue by chetan51** [DamnWidget/anaconda#238]
When I use the "Run test under cursor" feature, I see the following error in my Sublime Text console:

	Traceback (most recent call last):
	  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
	    return self.run(edit)
	  File "/Users/Chetan/Library/Application Support/Sublime Text 3/Packages/Anaconda/commands/test_runner.py", line 140, in run
	    command = self._prepare_command()
	  File "/Users/Chetan/Library/Application Support/Sublime Text 3/Packages/Anaconda/commands/test_runner.py", line 26, in wrapper
	    result = func(self)
	  File "/Users/Chetan/Library/Application Support/Sublime Text 3/Packages/Anaconda/commands/test_runner.py", line 176, in _prepare_command
	    return ' '.join(command)
	TypeError: sequence item 1: expected str instance, NoneType found

**Comment by DamnWidget** [comment]
This error has been fixedin branch fix238, waiting for release v1.3.6

**Comment by chetan51** [comment]
Thanks!
