### ISSUE TITLE
module object has no attribute 'exists'

### ISSUE THREAD

**Issue by proteusvacuum** [DamnWidget/anaconda#322]
After the latest update, I am getting the following error. I haven't changed anything with my config files.
Uninstall and reinstall doesn't fix it. 

> 2015-05-12 14:04:02,310 'module' object has no attribute 'exists'
2015-05-12 14:04:02,310 Traceback (most recent call last):
  File "/Users/farid/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 183, in start
    self.start_json_server()
  File "/Users/farid/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 72, in start_json_server
    self.build_server()
  File "/Users/farid/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 255, in build_server
    if not os.exists(path):
AttributeError: 'module' object has no attribute 'exists'
2015-05-12 14:04:02,510 'module' object has no attribute 'exists'
2015-05-12 14:04:02,510 Traceback (most recent call last):
  File "/Users/farid/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 183, in start
    self.start_json_server()
  File "/Users/farid/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 72, in start_json_server
    self.build_server()
  File "/Users/farid/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 255, in build_server
    if not os.exists(path):
AttributeError: 'module' object has no attribute 'exists'

**Comment by DamnWidget** [comment]
Sorry, my fault, last release (just pushed) should solve it

**Comment by proteusvacuum** [comment]
thanks for the speedy response!!
