### ISSUE TITLE
anaconda_pep8.py: NoneType object is unsubscriptable

### ISSUE THREAD

**Issue by lovette** [DamnWidget/anaconda#341]
Anaconda updated itself this morning and I noticed this `unsubscriptable` error in anaconda_jsonserver.log after starting ST the first time:

```
anaconda new install
2015-06-16 12:02:45,437: DEBUG   : bind: address=('localhost', 56670)
2015-06-16 12:02:45,437: DEBUG   : listen: backlog=5
2015-06-16 12:02:45,438: INFO    : Anaconda Server started in port 56670 for PID 30383 with cache dir /Users/Lance/Library/Caches/Jedi/webhook and extra paths /Users/Lance/sites/webhook,/Users/Lance/shared-packages,/Users/Lance/virtualenvs/webhook/lib/python2.6/site-packages
2015-06-16 12:02:45,441: INFO    : Incomming connection from ('127.0.0.1', 56703)
2015-06-16 12:02:45,442: INFO    : Incomming connection from ('127.0.0.1', 56704)
2015-06-16 12:02:45,461: INFO    : client requests: lint
2015-06-16 12:02:45,593: INFO    : About push back to ST3: {"vid": 67, "errors": [{"regex": "((and|or|not|if|elif|while|in)\\s+|[+\\-*^%%<>=\\(\\{])*\\s*(?P<underline>[\\w\\.]*attachment\\_basename[\\w]*)", "level": "W", "raw_error": "undefined name 'attachment_basename'", "len": 19, "lineno": 494, "offset": 56, "message": "Undefined name %r", "underline_range": false}], "uid": "13d06d11bf5e404cb9792764edb2c9d5", "success": true}

2015-06-16 12:02:45,594: INFO    : client requests: lint
2015-06-16 12:02:45,601: ERROR   : 'NoneType' object is unsubscriptable
2015-06-16 12:02:45,602: DEBUG   : ['Traceback (most recent call last):', '  File "/Users/Lance/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/commands/pep8.py", line 31, in run', '    self.settings, self.code, self.filename),', '  File "/Users/Lance/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/../../anaconda_lib/linting/anaconda_pep8.py", line 56, in lint', "    code, filename, settings.get('pep8_rcfile'), **check_params", '  File "/Users/Lance/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/../../anaconda_lib/linting/anaconda_pep8.py", line 122, in check', '    pep8.Checker(filename, good_lines, options=options).check_all()', '  File "/Users/Lance/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/../../anaconda_lib/linting/pep8.py", line 1542, in check_all', '    self.check_logical()', '  File "/Users/Lance/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/../../anaconda_lib/linting/pep8.py", line 1448, in check_logical', '    self.report_error(offset[0], offset[1], text, check)', '  File "/Users/Lance/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/../../anaconda_lib/linting/anaconda_pep8.py", line 100, in error', '    filename, col, offset, code, message, levels[code[0]]', "TypeError: 'NoneType' object is unsubscriptable"]
2015-06-16 12:02:45,664: INFO    : About push back to ST3: {"vid": 69, "errors": "'NoneType' object is unsubscriptable", "uid": "19d3509b495047f99b6025b795b6b980", "success": false}
```

**Comment by DamnWidget** [comment]
No changes were made to the linters, can you grep for that error to see if you had it before the update?

**Comment by lovette** [comment]
It does not, but I deleted all my logs yesterday while looking into #340 so the log file only includes yesterday. This morning I uninstalled and reinstalled Anaconda to see if it helped with any of the issues I'm having with it at the moment, and noticed the error then.

**Comment by DamnWidget** [comment]
I never replicated this error myself, I am calling for feed back here as a commit was made on Nov the 12th of past year so I still don't know if I can close this issue or not.

**Comment by lovette** [comment]
My current logs go back to Feb. and I don't see this error. Consider it resolved.

**Comment by DamnWidget** [comment]
Done
