### ISSUE TITLE
Anaconda gives unhelpful error messages when it can't find python ("Connection refused" or "AttributeError: 'NoneType' object has no attribute 'replace'")

### ISSUE THREAD

**Issue by haberdashPI** [DamnWidget/anaconda#347]
Hi, I'm having trouble using anaconda. After installing anaconda, any anaconda command I make brings up the following error in Sublime Text 3 (build 3083). 

```
ConnectionRefusedError: [Errno 61] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/Users/davidlittle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/Users/davidlittle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/Users/davidlittle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
```

**Comment by DamnWidget** [comment]
Looks like the ST3 plugin_host can't connect to "localhost" in your machine or you have configured anaconda in debug mode and you didn't started a server in the port 9999

Sometimes after updates, OS X messes up it's hosts file, that can make that problem to appears, take a look in [here](http://osxdaily.com/2014/04/12/restore-original-hosts-file-mac/)

**Comment by haberdashPI** [comment]
Thanks for the help. It does indeed look like my `/etc/hosts file` was missing the last line (`f380::1%lo0	localhost`). However, once I fix that, I'm now getting a different set of errors. 

- If I use "Goto Definition" or "Find Usages" I get no response. (There are some `no such prop content_margin` messages in the console but I get those regardless of whether I have anaconda installed or not).

- If I use "Show Documentation" I get: `'NoneType' object has no attribute 'replace'`

- If I use McCabe complexity check I get: 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/Users/davidlittle/Library/Application Support/Sublime Text 3/Packages/Anaconda/commands/mccabe.py", line 28, in run
    Worker().execute(Callback(on_success=self.prepare_data), **data)
  File "/Users/davidlittle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 438, in execute
    worker.start()
  File "/Users/davidlittle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 164, in start
    python_interpreter
  File "/Users/davidlittle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 33, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "/Users/davidlittle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 67, in _parse_tpl
    cmd = cmd.replace('\\', '\\\\')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by DamnWidget** [comment]
I think your Python interpreter is set to an empty string

**Comment by haberdashPI** [comment]
Ah hah! That wasn't the problem, but that pointed me in the right direction. The interpreter was set to "python". (From the default settings). When I change this to the absolute path of my python binary (`//anaconda/bin/python` in my case) or, alternatively, if I launch Sublime Text from the command line rather than through my app launcher (Alfred v2 in my case) it now works.

**Comment by pradyunsg** [comment]
I think this can now be closed.
