### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by alimony** [DamnWidget/anaconda#353]
I'm suddenly seeing the same issue as #297 again. Have anything changed regarding jedi etc.?

**Comment by DamnWidget** [comment]
the complete list of changes form version 1.4.7 to 1.4.11 can be check in git with `git log v1.4.3..v1.4.4`, there has been an update to Jedi but probably your issue is not a regression of #297.

Can you provide more information?, console logs and jsonserver logs?

**Comment by alimony** [comment]
It works fine when running jsonserver in debug mode. This is from the ST3 console when running normally and getting the error:

```
ERROR:root:[Errno 61] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/Users/markus/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/Users/markus/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/Users/markus/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by DamnWidget** [comment]
Well, is hard to say with that information, make sure that your configured python interpreter can run the jsonserver.py script.

**Comment by alimony** [comment]
How do I test that properly? I did `cd` into `anaconda_server` and tried `python3 jsonserver.py`, what should I pass as port and PID?

**Comment by DamnWidget** [comment]
Take a look [here](https://github.com/DamnWidget/anaconda/blob/master/Anaconda.sublime-settings#L62-L83)

**Comment by alimony** [comment]
As I mentioned previously, when running the server in debug mode everything works fine.

**Comment by DamnWidget** [comment]
The only explanation is that your configured interpreter path is wrong or is being override in a more specific configuration level. The only difference between run jsonserver.py from the command line yourself using debug mode is that anaconda doesn't try to use your configured python interpreter to run it as it just try to attach the plugin to the port tat is defined in the configuration for debug.

As I said before, make sure that your configured python interpreter is able to run the JsonServer and it's a valid python interpreter. 

That connection refused could be because ST3 can't connect to "localhost" (for whatever reason, normally misconfigured environment) and/or because the Python interpreter is crashing or is not able to run the JsonServer.

**Comment by pradyunsg** [comment]
@DamnWidget Do you think it might be a good idea to cover the erroring line in a try-except and provide a custom exception with a nicer message?

```python
try:
    self.sock.connect(address)
# You could use ConnectionRefusedError here; this is more generic
except IOError:
    raise Exception("Anaconda could not connect to it's linting Python process.")

**Comment by DamnWidget** [comment]
Any updates here?

**Comment by pradyunsg** [comment]
This looks like a hisenbug.

@alimony You might try deleting Sublime Text cache. It might also be worthwhile to post the debug output of the json server.

**Comment by pradyunsg** [comment]
*hisenbug. I can't edit from my phone.

I should sleep, it's nearly 3.

**Comment by DamnWidget** [comment]
Yeah, a heisenbug and a pain in the ass as well.

**Comment by mcdevitts** [comment]
I'm having a similar issue (I think) as described above. Although mine manifests itself in a different fashion. When launching sublime I get the following error message as others have described previously:
![image](https://cloud.githubusercontent.com/assets/13813076/20725897/a83fe18a-b630-11e6-94fb-39cba910acbf.png)

However, Anaconda does not work properly after that error message. When I launch sublime while running the jsonserver in debug mode, everything works fine. I've uninstalled and reinstalled both sublime and anaconda (as well as wiping the settings files).

OS: Windows 7
Sublime: Build 3126
Anaconda: 2.1.10
Python: 3.4.5

Any ideas here?

**Comment by DamnWidget** [comment]
Looks like your `python_interpreter` may be incorrect @mcdevitts

**Comment by DamnWidget** [comment]
Try `"python_interpreter":  "C:\\Miniconda3\\python.exe"`

**Comment by mcdevitts** [comment]
@DamnWidget same issue.

**Comment by DamnWidget** [comment]
Make sure you dont have the `jsonserver_debug` is set as `false` in your
settings

**Comment by mcdevitts** [comment]
My jsonserver_debug setting is set to false.

I only had it set to true when I tried launching a separate jsonserver (which worked).

**Comment by DamnWidget** [comment]
Look at `%APPDATA%\\Anaconda\\Logs\\` to see if there is something in the logs.

**Comment by mcdevitts** [comment]
There's a set of logs in "test" folder from when I launched the jsonserver in debug mode. However, other than that there are no logs in that folder.

Looking around at issues it seems like I'm having a similar problem as @JPCoding in this thread:
https://github.com/DamnWidget/anaconda/issues/514

As in, I don't believe the jsonserver is even starting. Should this server show up as a python.exe process in the task manager?

**Comment by DamnWidget** [comment]
Yes, it will be shown as a Python process in the task manager, by the way, in @JPCoding case was because the directory where his project was stored contained some unicode characters (that is not a problem on POSIX not sure why it is on Windows), maybe worth to take a look

**Comment by AKFourSeven** [comment]
Hi, I am having a similar issue and I was wondering if python version should be 3 or 2.x or whether it did not matter ?
