### ISSUE TITLE
Sublime Freezes

### ISSUE THREAD

**Issue by MikeSmith12222** [DamnWidget/anaconda#357]
Hi guys,

I got anaconda running in ST3 and I do love it's features. It feels really good having it there to help me.

THE PROBLEM is in the state of my current project it freezes ST complety. I need to force-quit Sublime-Text and manually delete the anaconda folder out of the ``packages`` Folder.

I have the feeling that it has to do with the DocStrings and restructured Text stuff I do in my project. I have ReadTheDocs Sphinx running and of course those .rst docs are located next to the .py files. Also I heavily document my code within the .py files.

Right now Anaconda is unusable and I need to deinstall it. Those crashes keep me from being productive.

Is there anything I can do to make anaconda run more stable?
Can I maybe EXCLUDE the **docs directory** (with those .rst files) from being processed by anaconda?

I am looking forward for your tips

Kind regards
Mikey

**Comment by DamnWidget** [comment]
Hi Mikey.
Are you sure that is the problem? Mamba (http://www.pymamba.com) has lot of
documentation including .rst files and I never had any type of problems.

Disable the "enable_signatures_tooltip" option in your config file. If that
solves the problem is just a bug in the immature tooltip support in ST3

**Comment by DamnWidget** [comment]
Any update here?

**Comment by banderson5586** [comment]
I have the same issue. Fresh install of ST3 3083. I open a python file without anaconda and it works fine. As soon as I install anaconda and try to open any python file ST3 immediately locks and I have to force-quit.

**Comment by DamnWidget** [comment]
Can I have a copy of the file/project?

On 6 November 2015 at 20:17, banderson5586 <notifications@github.com> wrote:

> I have the same issue. Fresh install of ST3 3083. I open a python file
> without anaconda and it works fine. As soon as I install anaconda and try
> to open any python file ST3 immediately locks and I have to force-quit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/357#issuecomment-154521048>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by banderson5586** [comment]
Literally anything. I took basic string manipulations examples, paste them in a file and it works fine. When I try to save as a file with .py extension, Sublime locks.

**Comment by arruda** [comment]
Same as @banderson5586  here:
* open ST3 window, 
* create new file, 
* write `import os`
* set file type as `python`
* **ST3 freezes for about 40 secs**

Larger .py files get stuck more time.

**Comment by clawoflight** [comment]
Same problem here.

`Ctrl+Shift+P` `set syntax python` --> ST3 slows to a crawl and/or freezes.
Running 3083 as well.

**Comment by banderson5586** [comment]
Any update? Seems this is a repeatable issue affecting multiple users.

**Comment by DamnWidget** [comment]
We need much more information to even start to look at this issue. A copy of your ST3 python console log and the contents of your cache anaconda-jsonserver log is needed.

The logs can be found in:
* Linux: ~/.cache/jedi/<your_project_name>/anaconda_jsonserver.log
* Windows: %APPDATA%\Jedi\Jedi\<your_project_name>\anconda_jsonserver.log
* OS X: ~/Library/Caches/Jedi/<your_project_name>/anaconda_jsonserver.log

A guess with no more information is that the Sublime Text 3 python socket is not able to connect to your `localhost`

**Comment by clawoflight** [comment]
This is what the ST3 console shows, which seems to support your guess:

```
2015-12-21 15:57:52,310 [Errno 111] Connection refused
2015-12-21 15:57:52,311 Traceback (most recent call last):
  File "/home/bennett/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/home/bennett/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/home/bennett/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by DamnWidget** [comment]
Hi @clawoflight 

As I guessed seems like your ST3 embedded Python interpreter is not able to connect to your localhost, that can happen because two resons:

1. The `localhost` address is not accessible for any reason
2. The Sublime Text 3 is unable to start the JsonServer

I assume that you are under GNU/Linux (as per the `~/.cache/jedi` in your answer) so make sure you have a valid entry to `localhost` in your `/etc/hosts` file (something like `127.0.0.1       localhost`) 

To check if your ST3 Python embedded interpreter is able to connect to `localhost` follow the steps below:
1. Install netcat if you don't have it already (sudo apt-get install netcat for debian based, sudo pacman -S netcat for ArchLinux based, sudo yum install netcat in RedHat based or emerge --ask --verbose netcat in Gentoo based)
2. Open a terminal window and write: `nc -l -p 1234` that will make netcat to listen to anything that is sent to the port 1234 in your local machine
3. Open the Sublime Text 3 console and write: `>>> import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('localhost', 1234)); s.send(bytes('Hello World!\n', 'utf8')); s.close()`

If your ST3 can connect to your local machine you will get a `Hello World!` in your terminal and the netcat that we did set up earlier will be now closed.

Test that and come back with the result.

**Comment by clawoflight** [comment]
Thanks for your help!
I had a valid line for localhost but none with my hostname.
However, the netcat test worked, but I still get the exact same error as soon as I switch the syntax to python.

**Comment by DamnWidget** [comment]
Can you check if there is one (ore m ore) jsonserver.py process in your system using `ps aux | grep jsonserver.py`?

Can you paste a full ST3 console log report into a gist or pastebin like?

**Comment by clawoflight** [comment]
I do not have any running jsonserver.py process.

The log is uploaded [here](https://vps1.piater.name/commie/#dN4WOaeY). I copied it after re-starting ST3, opening a new tab, and setting the syntax to python.

**Comment by banderson5586** [comment]
Thanks for the additional info. For me it was not having a localhost entry in /etc/hosts. Once I added that everything works fine.

**Comment by DamnWidget** [comment]
Can remove/disable SublimeLinter and try again?

**Comment by clawoflight** [comment]
I disabled all SublimeLinter packages and restarted, but I get the same `Errno: 111 connection refused` error.

**Comment by clawoflight** [comment]
So... I opened another project to start working on it and noticed that Anaconda works perfectly.
I also have a running jsonserver.py process.

After examining the differences between this project and my previous tests, I only see one significant difference: this project has (exactly one) added folder while my "default", day-by-day project has none.

Does Anaconda require a working directory? If so, this issue can be closed as both my and @banderson5586's problem are solved.

**Comment by DamnWidget** [comment]
Well, anaconda should be able to work for any project out of the box. ST3 added some kind of cache bug in recent versions that some times affect in very weird circumstances the way that anconda loads and detects your project files.

Probably is related with that, unfortunately when this problem appears is really hard to diagnose it or even replicate so it's showing himself as a very hard to detect/fix problem. I guess you can close this if you both are satisfied.

**Comment by clawoflight** [comment]
That sounds like it could be the issue, at least I know why it happens now (and I can do my work on the project :) )

I don't have the permissions to close it. @banderson5586 @thebarty are your problems both resolved?

@DamnWidget you might want to label/remember this issue somehow in case there are more problems with that cache bug.

**Comment by arruda** [comment]
@clawoflight when you say you have one added folder, you mean like this:
`you-project.sublime-project`:
```
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "."
		}
	],
```
It would be nice if I could understand what you meant by that, so that I could test in my PC and see if now my Anaconda will go back to live.

**Comment by clawoflight** [comment]
@arruda Yeah, I have this entry in that project:

```
"folders":
	[
		{
			"path": "/home/bennett/Github/MorgenLicht"
		}
	],
```

**Comment by dufferzafar** [comment]
I am having similar issues. This is what my sublime log shows:

```
ERROR:root:[Errno 111] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/home/dufferzafar/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/home/dufferzafar/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/home/dufferzafar/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by ClericPy** [comment]
thank a lot, removing ~/.cache/jedi makes sense, this error because of this folder's root authority, fix this makes ok. Finally I don't need to use anaconda under the sudo subl

**Comment by DamnWidget** [comment]
Why your `~/.cache/jedi` directory was owned by root?

**Comment by lunring** [comment]
I have same problem here，But I found that when I changed  DNS,  anaconda back to live, but I don't know why  this happen

**Comment by DamnWidget** [comment]
Probably your localhost was resolving to the wrong address or to the IPV6 version
