### ISSUE TITLE
Infinite recursion happening on Windows, but not Linux in Anaconda3

### ISSUE THREAD

**Issue by aewhatley** [DamnWidget/anaconda#372]
I am running a program that for some reason goes into an infinite recursion on Windows, but not on Linux. Here is the traceback:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Alexander\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Alexander\Anaconda3\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
  File "C:\Users\Alexander\Anaconda3\lib\asyncore.py", line 411, in __getattr__

Is this an issue with Windows, or with the python? Thanks.

**Comment by DamnWidget** [comment]
That doesn't looks very nice but I am afraid that this has nothing to do with our project at all...
