### ISSUE TITLE
Pyflakes linting does not work with unicode paths 

### ISSUE THREAD

**Issue by andopaju** [DamnWidget/anaconda#399]
Steps to reproduce:
1. Open file with path for example: C:\Äabc\file.txt
2. Linting does not work, crashes

OS: Windows 7

**Comment by DamnWidget** [comment]
First thing first

Which Sublime Text Build you are using?
Which anaconda version?
Which options are you using for the linter?
How do you know is "crashing"?
Do you have any log file that we can read?

Thanks.

**Comment by andopaju** [comment]
Build 3083
Latest anaconda version (1.4.15)
Linter options:
```
{
    "pep8": false,
    "python_interpreter":"C:\\python-27\\python.exe",
}
```
With "crashing" I meant no error is shown in the bottom of the screen or anywhere - this part of the sentence was unnecessary and can be ignored.

Snippet from log when linted:
```
2015-11-12 14:29:29,056: INFO    : client requests: lint
2015-11-12 14:29:29,056: ERROR   : __init__() takes exactly 6 arguments (4 given)
2015-11-12 14:29:29,058: DEBUG   : ['Traceback (most recent call last):', '  File "C:\\Sublime Text Build 3083 x64\\Data\\Packages\\Anaconda\\anaconda_server\\commands\\pyflakes.py", line 31, in run', '    self.settings, self.code, self.filename),', '  File "C:\\Sublime Text Build 3083 x64\\Data\\Packages\\Anaconda\\anaconda_server\\handlers\\../../anaconda_lib\\linting\\anaconda_pyflakes.py", line 44, in lint', '    errors.extend(self.check(code, filename, pyflakes_ignore))', '  File "C:\\Sublime Text Build 3083 x64\\Data\\Packages\\Anaconda\\anaconda_server\\handlers\\../../anaconda_lib\\linting\\anaconda_pyflakes.py", line 61, in check', '    return [PyFlakesError(filename, FakeLoc(), error.args[0])]', 'TypeError: __init__() takes exactly 6 arguments (4 given)']
2015-11-12 14:29:29,059: INFO    : About push back to ST3: {"vid": 15, "errors": "__init__() takes exactly 6 arguments (4 given)", "uid": "ed3caba9e23e425a82bc73dc0ccffba3", "success": false}
```
Other paths work fine, only unicode paths have this problem.

**Comment by DamnWidget** [comment]
Thank you for the details I will take a look into it as soon as I can.

**Comment by andopaju** [comment]
Same problem with McCabe, only log is different:
```
2015-11-13 09:24:58,655: INFO    : client requests: mccabe
2015-11-13 09:24:58,655: ERROR   : 'ascii' codec can't encode character u'\xc4' in position 13: ordinal not in range(128)
2015-11-13 09:24:58,655: DEBUG   : ['Traceback (most recent call last):', '  File "C:\\Sublime Text Build 3083 x64\\Data\\Packages\\Anaconda\\anaconda_server\\commands\\mccabe.py", line 30, in run', "    'errors': self.mccabe.get_code_complexity(self.threshold),", '  File "C:\\Sublime Text Build 3083 x64\\Data\\Packages\\Anaconda\\anaconda_server\\handlers\\../../anaconda_lib\\linting\\anaconda_mccabe.py", line 40, in get_code_complexity', '    if self.tree is not None:', '  File "C:\\Sublime Text Build 3083 x64\\Data\\Packages\\Anaconda\\anaconda_server\\handlers\\../../anaconda_lib\\linting\\anaconda_mccabe.py", line 32, in tree', "    return compile(code, self.filename, 'exec', ast.PyCF_ONLY_AST)", "UnicodeEncodeError: 'ascii' codec can't encode character u'\\xc4' in position 13: ordinal not in range(128)"]
```

**Comment by DamnWidget** [comment]
I can not replicate this behavior.

![can_not_replicate](https://cloud.githubusercontent.com/assets/329766/11146274/cd0b94f4-8a04-11e5-8bd4-bc63563a57e6.png)

Anyone else is having this problem?

**Comment by andopaju** [comment]
adding
``` python
            filename = filename.encode('utf8')
```
before 
``` python
 tree = compile(code, filename or '', 'exec', _ast.PyCF_ONLY_AST)
```
in anaconda_pyflakes.py fixes PyFlakes for me and similar fix for anaconda_mccabe.py fixes it as well.
Maybe it's a combination of Windows + Python 2.7 interpreter?
