### ISSUE TITLE
All functionalities not working  - Errno9 Bad File Descriptor

### ISSUE THREAD

**Issue by gtalarico** [DamnWidget/anaconda#408]
Linting, PEP, and autocomplete are not working.
Also typing in any Python document is sluggish (delay between letters showing up, etc) 
When I disable Anaconda, typing works as expected again. 

Sublime 3 on Ubuntu 14.04 on Macbook Pro kernel 3.18
I have tried removing and reinstalling package through package manager, no luck.

Log below after trying to run any Anaconda action. Any ideas?

```
[...]
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-12-07 02:31:56, next run at 2015-12-07 03:31:56 or after
ERROR:root:Unhandled exception in poll, restarting the poll request
ERROR:root:[Errno 9] Bad file descriptor
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/home/gtalarico/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 295, in inner_loop
ERROR:root:    poll()
ERROR:root:  File "/home/gtalarico/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 272, in poll
ERROR:root:    handler.send()
ERROR:root:  File "/home/gtalarico/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 129, in send
ERROR:root:    sent = self.sock.send(self.outbuffer)
ERROR:root:OSError: [Errno 9] Bad file descriptor
ERROR:root:Unhandled exception in poll, restarting the poll request
ERROR:root:[Errno 9] Bad file descriptor
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/home/gtalarico/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 295, in inner_loop
ERROR:root:    poll()
ERROR:root:  File "/home/gtalarico/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 272, in poll
ERROR:root:    handler.send()
ERROR:root:  File "/home/gtalaricof/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 129, in send
ERROR:root:    sent = self.sock.send(self.outbuffer)
ERROR:root:OSError: [Errno 9] Bad file descriptor
```

**Comment by gtalarico** [comment]
Found the bug.
I just realized that it was happening in just one file. I deleted parts of it, until I got to a code block that had the symbol: "FF" (Form feed character). I delete the character, all functionalities work again.
http://www.fileformat.info/info/unicode/char/000c/index.htm
The pasted the character into my code as I am trying to replace them out of a text document.

**Comment by DamnWidget** [comment]
The exception seem to happen in the poll call itself, probably that code has some special meaning for the socket.

**Comment by rbinnun2** [comment]
@gtalarico, which file did you make the replacement on?
