### ISSUE TITLE
Anaconda couldn't run linter

### ISSUE THREAD

**Issue by yrunts** [DamnWidget/anaconda#411]
I have the next error trying to use Anaconda (v1.4.16 installed using package manager) with Sublime Text 3 on Mac OS El Captain. 

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 208, in on_load
    callback.on_load(v)
  File "/Users/yr/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 76, in on_load
    self.run_linter(view)
  File "/Users/yr/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 344, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/yr/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 438, in execute
    worker.start()
  File "/Users/yr/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 164, in start
    python_interpreter
  File "/Users/yr/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 45, in update_interpreter_build_system
    'build_systems': [self._parse_tpl(cmd)]
  File "/Users/yr/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 67, in _parse_tpl
    cmd = cmd.replace('\\', '\\\\')
AttributeError: 'NoneType' object has no attribute 'replace'

Something similar to this but as I understand it is already fixed - https://github.com/DamnWidget/anaconda/issues/283

**Comment by yrunts** [comment]
I've tried clean version of Sublime, just installed Package Control(https://packagecontrol.io/installation) and Anaconda. The issue is still reproduces.

**Comment by DamnWidget** [comment]
Seems like your Python interpreter is set to an empty string. Set it to a valid Python binary.

**Comment by yrunts** [comment]
Thanks for answering,
"python_interpreter": "python", - should I change that value?

**Comment by DamnWidget** [comment]
Sorry for the delay, I've been busy with life things. Point your python interpreter t the python interpreter that you are working with.

A good start will be to read the regarding documentation in http://damnwidget.github.io/anaconda/anaconda_settings/

**Comment by yrunts** [comment]
The issue it fixed. Thanks.
