### ISSUE TITLE
ERROR:root:'NoneType' object has no attribute 'poll'

### ISSUE THREAD

**Issue by overmiao** [DamnWidget/anaconda#437]
After the latest update, I am getting the following error. I haven't changed anything with my config files.
Uninstall and reinstall doesn't fix it.

> ERROR:root:'NoneType' object has no attribute 'poll'
> ERROR:root:Traceback (most recent call last):
>   File "/Users/overmiao/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 183, in start
>     self.start_json_server()
>   File "/Users/overmiao/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 65, in start_son_server
>     if self.server_is_healthy():
>   File "/Users/overmiao/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 103, in server_is_healthy
>     if self.process.poll() is None:
> AttributeError: 'NoneType' object has no attribute 'poll'

**Comment by overmiao** [comment]
I reinstall Anaconda today, and it worked fine!
