### ISSUE TITLE
UnboundLocalError: local variable 'python_interpreter' referenced before assignment

### ISSUE THREAD

**Issue by divinites** [DamnWidget/anaconda#468]
After disabling auto-completion(I am using YCMD to auto-complete instead of Anaconda's built-in), once I open a py file, the console show this:

```
Traceback (most recent call last):
  File "/Users/divinites/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/Users/divinites/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/Users/divinites/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 252, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "/Users/divinites/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 76, in on_load
    self.run_linter(view)
  File "/Users/divinites/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 344, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/divinites/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 447, in execute
    worker.start()
  File "/Users/divinites/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 198, in start
    python_interpreter,
UnboundLocalError: local variable 'python_interpreter' referenced before assignment
```

**Comment by DamnWidget** [comment]
The traceback is not related with auto completion being disabled but with anaconda being unable to connect to your local host. Check that your ST3 is able to connect to your local host using "localhost" as address.

Btw anaconda and ycm both use the same library to offer auto completion (jedi library) so there is not much benefit to use ycm auto completion over anaconda one as they should have the same capabilities, the only difference is that anaconda has been around for a while already.

**Comment by divinites** [comment]
Thanks, I think that I found the error, it is about localhost,  issue closed.

btw: yes, ycmd and anaconda both use Jedi, I use ycmd by default simply because I need to switch back and forth between rust and python. 

Cheers.

**Comment by DamnWidget** [comment]
I am thinking in add another plugin "anaconda_rust" as I am doing some things in rust now in my free time so probably we will have native support for it in some moment in the future.

**Comment by divinites** [comment]
That would be great!  I am looking forward to your new plug-in about rust!
