### ISSUE TITLE
Connection Error after today's update.

### ISSUE THREAD

**Issue by pkucmus** [DamnWidget/anaconda#472]
Hello.

I get the following error:

```
ERROR:root:error detected while connecting with JsonServer!python interpreter: /home/pkucmus/.virtualenvs/kaka/bin/pythonconnecting port: 43752check https://github.com/DamnWidget/anaconda/wiki/Connection-Refused-Information
ERROR:root:[Errno 111] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/home/pkucmus/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/home/pkucmus/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 38, in __init__
    EventHandler.__init__(self, (host, port))
  File "/home/pkucmus/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

I followed the https://github.com/DamnWidget/anaconda/wiki/Connection-Refused-Information and everything looks behave as anticipated in the OK path with the exception that I removed my ~/.cache/jedi directory trying another fix and it's not getting recreated so I have no logs to paste.

```
>>> import Anaconda
>>> Anaconda.version.version
(1, 4, 20)
```

**Comment by pkucmus** [comment]
Here's my `sublime-project` file:
```
{
    "build_systems":
    [
        {
            "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
            "name": "Anaconda Python Builder",
            "selector": "source.python",
            "shell_cmd": "\"/home/pkucmus/.virtualenvs/kaka/bin/python\" -u \"$file\""
        }
    ],
    "folders":
    [
        {
            "path": "/home/pkucmus/something/"
        }
    ],
    "settings":
    {
        "pep8_max_line_length": 99,
        "python_interpreter": "/home/pkucmus/.virtualenvs/kaka/bin/python",
        "rulers":
        [
            99
        ],
        "wrap_width": 100
    }
}
```

**Comment by DamnWidget** [comment]
Hi @pkucmus 

I understand that it was working for you before or it never worked?

**Comment by pkucmus** [comment]
Yes it was working till a few hours ago.

**Comment by pkucmus** [comment]
I reverted to 
```
>>> import Anaconda
>>> Anaconda.version.version
(1, 4, 18)
```
and works ok now.

**Comment by DamnWidget** [comment]
That's cool but I would prefer if we can go to the bottom of your issue and fix it as it can possible affecting other users, I can't replicate it myself.

Can you give me more information about your environment?

Which version of Python is the one in your virtualenv?

**Comment by DamnWidget** [comment]
Looks like I broke Python2 support!!!!

**Comment by pkucmus** [comment]
Sure, my colleagues (sitting next to me) are starting to suffer the same thing.
```
$ python
Python 2.7.10 (default, Sep 17 2015, 13:36:31) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Using Xubuntu 14.04.

**Comment by Kzinglzy** [comment]
@pkucmus how did you reverted to old version?.
 I got a more terrible situation which my sublime is very very slow after this update..

**Comment by medariox** [comment]
@Kzinglzy 
Same here. It got painfully slow just after the update.

**Comment by pkucmus** [comment]
I removed it with package install (as that's the way it was installed). Then I pulled an older version from https://github.com/DamnWidget/anaconda/tree/v1.4.19 zip. Then you extract into your `~/.config/sublime-text-3/Packages/` (if Linux). I additionally changed the directory name from anaconda-1.19... to Anaconda.

**Comment by DamnWidget** [comment]
Fix incoming guys

**Comment by pkucmus** [comment]
Tested, working :+1: thanks!

**Comment by DamnWidget** [comment]
The fix will be available in Package Control in a few minutes.

Thank you for the quick feedback guys.

**Comment by Kzinglzy** [comment]
Thanks 💯

**Comment by Kzinglzy** [comment]
this happend again after update to v1.4.28...

``` python
Unexpected error in `server_is_active`: [Errno 8] nodename nor servname provided, or not known
ERROR:Anaconda.anaconda_lib.worker:Unexpected error in `server_is_active`: [Errno 8] nodename nor servname provided, or not known
ERROR:root:error detected while connecting with JsonServer!python interpreter: /usr/local/bin/pythonconnecting port: 49438check https://github.com/DamnWidget/anaconda/wiki/Connection-Refused-Information
ERROR:root:[Errno 8] nodename nor servname provided, or not known
ERROR:root:Traceback (most recent call last):
  File "/Users/kzing/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/Users/kzing/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 38, in __init__
    EventHandler.__init__(self, (host, port))
  File "/Users/kzing/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
