### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Gabriel-p** [DamnWidget/anaconda#473]
Starting today, after an update from this package, I get not linting and this error shows in the console:

```
ERROR:root:error detected while connecting with JsonServer!python interpreter: /home/gabriel/.pyenv/versions/py-2.7.8/bin/pythonconnecting port: 49359check https://github.com/DamnWidget/anaconda/wiki/Connection-Refused-Information
ERROR:root:[Errno 111] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/home/gabriel/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/home/gabriel/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 38, in __init__
    EventHandler.__init__(self, (host, port))
  File "/home/gabriel/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

I'm running SublimeText 3103.

**Comment by DamnWidget** [comment]
Fixed on version 1.4.21, please, update
