### ISSUE TITLE
Cannot autocomplete sys.stdout.flush()

### ISSUE THREAD

**Issue by AllanLRH** [DamnWidget/anaconda#509]
Cannot autocomplete `sys.stdout.flush()` – the `sys,stdout` works ok thouth.
Using Python 3 on mac (Anaconda Python disitibution, Python 3.5.2).

**Comment by DamnWidget** [comment]
Can't replicate it using Python 3.5.2, try this:

- Open a Terminal
- Go to the Anaconda directory under your ST3 packages folder 
- cd into `anaconda_lib`
- run this command `python -c "import jedi; s = jedi.Script('import sys; sys.stdout.f', path='.'); print(s.completions())"`

If you get an output like: `[<Completion: fileno>, <Completion: flush>]` everything is fine with your installation, if you still don't get the completion to work in ST3, copy and paste the anaconda server logs for your on use project into a gist and link it.

**Comment by AllanLRH** [comment]
Where do I find the logs? Also, notice that I'm not working in a project.
Here are some output from my terminal:

```bash
py35)❯ pwd
/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib

~/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib
(py35)❯ ls -1
__init__.py
__pycache__
autopep
builder
callback.py
contexts.py
decorators.py
enum.py
helpers.py
import_validator.py
ioloop.py
jedi
jediusages.py
jsonclient.py
linting
persistent_list.py
progress_bar.py
tooltips.py
vagrant.py
worker.py

~/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib
(py35)❯ python --version
Python 3.5.2 :: Continuum Analytics, Inc.

~/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib
(py35)❯ python -c "import jedi; s = jedi.Script('import sys; sys.stdout.f', path='.'); print(s.completions())"
Traceback (most recent call last):
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/enum.py", line 367, in __getattr__
    return cls._member_map_[name]
KeyError: '_convert'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/api/__init__.py", line 16, in <module>
    from jedi.parser import Parser, load_grammar
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/__init__.py", line 21, in <module>
    from jedi.parser import tree as pt
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/tree.py", line 39, in <module>
    from jedi import cache
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/cache.py", line 30, in <module>
    from jedi import settings
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/settings.py", line 78, in <module>
    import platform
  File "/Users/allan/homeInstalled/miniconda2/envs/py35/lib/python3.5/platform.py", line 117, in <module>
    import sys, os, re, subprocess
  File "/Users/allan/homeInstalled/miniconda2/envs/py35/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/Users/allan/homeInstalled/miniconda2/envs/py35/lib/python3.5/signal.py", line 8, in <module>
    _IntEnum._convert(
  File "/Users/allan/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/enum.py", line 369, in __getattr__
    raise AttributeError(name)
AttributeError: _convert

~/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib
(py35)❯
```

**Comment by DamnWidget** [comment]
There is another user that uses the anaconda Python distribution that have the same problem with the enum. I will try to install it and reproduce the problem

**Comment by AllanLRH** [comment]
Then you should have a look at [Miniconda](http://conda.pydata.org/miniconda.html) – it's a lot smaller that the full blown Anaconda Python Distribution, and it doesn't require you to register (I installed in this way).
And the distribution comes with it's own package manager, Conda – hope it makes checking the problem easyier :)
