### ISSUE TITLE
So many `jsonserver.py` process after upgade to 2.0.1

### ISSUE THREAD

**Issue by nattster** [DamnWidget/anaconda#513]
After an upgrade to Anaconda 2.0.1, there are so many `jsonserver` process started.

```bash
ps ax | grep subl
14598 ?        Ssl    0:05 /opt/sublime_text/sublime_text
14666 ?        Sl     0:02 /opt/sublime_text/plugin_host 14598
14705 ?        Sl     0:01 python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj 14666
14761 ?        Sl     0:00 python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj 14666
14765 ?        Sl     0:00 python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj 14666
14771 ?        Sl     0:00 python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj 14666
14775 ?        Sl     0:00 python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj 14666
14859 ?        Sl     0:00 python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj 14666
14865 ?        Rl     0:00 python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj 14666
14869 ?        Sl     0:00 python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj 14666
```

## Log from sublime console

```
Package Control: Skipping automatic upgrade, last run at 2016-08-26 11:40:31, next run at 2016-08-26 12:40:31 or after
ERROR:root:Unhandled exception in poll, restarting the poll request
ERROR:root:[Errno 9] Bad file descriptor
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 298, in inner_loop
ERROR:root:    poll()
ERROR:root:  File "/home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 275, in poll
ERROR:root:    handler.send()
ERROR:root:  File "/home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 132, in send
ERROR:root:    sent = self.sock.send(self.outbuffer)
ERROR:root:OSError: [Errno 9] Bad file descriptor
```

**Version**
* Anaconda 2.0.1
* Sublime Text 3 (Build 3114)
* Ubuntu 14.04

**Comment by DamnWidget** [comment]
Can you gist and share the contents of ~/.local/shared/anaconda/tbh/logs/anaconda_jsonserver.log please?

**Comment by nattster** [comment]
anaconda_jsonserver.log -> https://gist.github.com/nattster/c7003ac032ab07be19e42cfe6c9b3861

**Comment by DamnWidget** [comment]
Seems like the jsonserver is crashing but for some reason we don't have any exception in the logs. I am gonna need you to start the server manually and paste any exception that is thrown to the standard output. To do so:

- Disable Anaconda plugin using Command Palette
- Close ST3 and make sure there is no jsonserver's running using `ps` 
- Open ST3 and get it's PID using `ps`
- In a terminal, `python -B /home/proj/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p tbh -e /home/proj/proj <STR_PID>` where STR_PID is the `pid` that you got in the previous step
- Enable Anaconda plugin using Command Palette
- Edit some Python file a bit and look at the terminal

**Comment by alexander-akhmetov** [comment]
> Seems like the jsonserver is crashing but for some reason we don't have any exception in the logs. I am gonna need you to start the server manually and paste any exception that is thrown to the standard output.

```
Received method: autocomplete, handler: jedi
<class 'handlers.jedi_handler.JediHandler'> handler retrieved from registry
error: uncaptured python exception, closing channel <__main__.JSONHandler connected '' at 0x105bbd758> (<type 'exceptions.UnicodeEncodeError'>:'ascii' codec can't encode characters in position 1277-1285: ordinal not in range(128) 

[/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py|read|83] 
[/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py|handle_read_event|449] 
[/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asynchat.py|handle_read|165] [/Users/user/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py|found_terminator|102] 
[/Users/user/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py|handle_command|122] 
[/Users/user/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py|run|30] 
[/Users/user/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/lib/anaconda_handler.py|run|48] 
[/Users/user/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py|autocomplete|77] 
[/Users/user/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py|script|47] 
[/Users/user/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py|jedi_script|58])
```

Perhaps the problem is here:
```

if self.debug is True:
    logging.debug(
        'jedi_script called with the following parameters '
        'source: {0}\nline: {1} offset {2}, filename: {3}'.format(
            source, line, offset, filename
        )
    )

```

`jsonserver_debug` is disabled, but `self.debug` is `True`. Another jsonserver.py process was started.

**Comment by DamnWidget** [comment]
I understand that the "perhaps" paragraph is in answer to the "no logs in the log file", nope, that is just for verbosity, I will take a look at the exceptions chain when I have time.

Seems like you have an unicode problem (my favourite). Can I know the context of your project? 

* The path containing your files use any non ASCII character?
* The code contains any non ASCII character?
* In your second log the OS is OS X in the first is a Linux box, can you explain to me?

**Comment by DamnWidget** [comment]
@nattster any update in your side?

**Comment by insanemainframe** [comment]
I have this problem too
>The code contains any non ASCII character?
Yes

**Comment by DamnWidget** [comment]
I will make a release later today to hopefully fix this issue.

**Comment by nattster** [comment]
@DamnWidget I'm running Anaconda 2.0.2, and perform the steps as you suggested:

```
error: uncaptured python exception, closing channel <__main__.JSONHandler connected '' at 0x7fb39dd2d3b0> (<type 'exceptions.UnicodeEncodeError'>:'ascii' codec can't encode characters in position 1899-1903: ordinal not in range(128) [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|449] [/usr/lib/python2.7/asynchat.py|handle_read|158] [/home/natt/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py|found_terminator|102] [/home/natt/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py|handle_command|122] [/home/natt/.config/sublime-text-3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py|run|30] [/home/natt/.config/sublime-text-3/Packages/Anaconda/anaconda_server/lib/anaconda_handler.py|run|48] [/home/natt/.config/sublime-text-3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py|doc|101] [/home/natt/.config/sublime-text-3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py|script|47] [/home/natt/.config/sublime-text-3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py|jedi_script|58])
```

After that, it spawn more `jsonserver`.
My source code contains UTF-8 text.

**Comment by DamnWidget** [comment]
Please, update your installation with v2.0.3, feel free to re-open if the issue persist (but add new logs)
