### ISSUE TITLE
Doesn't work anymore, 'module' object has no attribute 'expand_variables'

### ISSUE THREAD

**Issue by randomshinichi** [DamnWidget/anaconda#525]
```
startup, version: 3062 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/shinichi/Library/Application Support/Sublime Text 3/Packages
state path: /Users/shinichi/Library/Application Support/Sublime Text 3/Local
hardware concurrency: 4
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/shinichi/Library/Application Support/Sublime Text 3/Installed Packages
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 5 files for base name Main.sublime-menu
loading pointer bindings
loading bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 5 orphaned files: 0 total files: 179 cache hits: 174
pre session restore time: 0.344011
using gamma: 1.9 (err: 99.6544)
startup time: 0.436274
first paint time: 0.463757
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
loaded 837 snippets
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
reloading plugin WordCount.WordCount
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin Pretty JSON.PrettyJsonListeners
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 122, in on_activated
    self.run_linter(view)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 347, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 86, in execute
    worker = cls.hire(cls)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 31, in hire
    raw_interpreter = get_interpreter(active_view())
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 349, in get_interpreter
    return get_settings(view, 'python_interpreter', 'python')
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 204, in get_settings
    r = sublime.expand_variables(r, w.extract_variables())
AttributeError: 'module' object has no attribute 'expand_variables'
ERROR:root:Traceback (most recent call last):
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/commands/autoformat.py", line 79, in run
    Worker().execute(callback, **data)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 86, in execute
    worker = cls.hire(cls)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 31, in hire
    raw_interpreter = get_interpreter(active_view())
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 349, in get_interpreter
    return get_settings(view, 'python_interpreter', 'python')
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 204, in get_settings
    r = sublime.expand_variables(r, w.extract_variables())
AttributeError: 'module' object has no attribute 'expand_variables'

Package Control: Installing 1 upgrades
ignored packages updated to: [Anaconda, Vintage]
found 1 files for base name Default.sublime-theme
unloading plugin Anaconda.anaconda
reloading Packages/Anaconda/Anaconda.sublime-settings
unloading plugin Anaconda.setup
unloading plugin Anaconda.version
generating meta info summary
found 5 files for base name Default.sublime-keymap
found 4 files for base name Main.sublime-menu
reloading Packages/User/Package Control.sublime-settings
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
Package Control: Upgraded Anaconda to 2.0.6
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading plugin Anaconda.anaconda
reloading Packages/Anaconda/Anaconda.sublime-settings
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
generating meta info summary
found 6 files for base name Default.sublime-keymap
theme loaded
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
found 5 files for base name Main.sublime-menu
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 122, in on_activated
    self.run_linter(view)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 347, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 86, in execute
    worker = cls.hire(cls)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 31, in hire
    raw_interpreter = get_interpreter(active_view())
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 349, in get_interpreter
    return get_settings(view, 'python_interpreter', 'python')
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 204, in get_settings
    r = sublime.expand_variables(r, w.extract_variables())
AttributeError: 'module' object has no attribute 'expand_variables'
ERROR:root:Traceback (most recent call last):
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/commands/autoformat.py", line 79, in run
    Worker().execute(callback, **data)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 86, in execute
    worker = cls.hire(cls)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 31, in hire
    raw_interpreter = get_interpreter(active_view())
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 349, in get_interpreter
    return get_settings(view, 'python_interpreter', 'python')
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 204, in get_settings
    r = sublime.expand_variables(r, w.extract_variables())
AttributeError: 'module' object has no attribute 'expand_variables'

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 122, in on_activated
    self.run_linter(view)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 347, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 86, in execute
    worker = cls.hire(cls)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 31, in hire
    raw_interpreter = get_interpreter(active_view())
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 349, in get_interpreter
    return get_settings(view, 'python_interpreter', 'python')
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 204, in get_settings
    r = sublime.expand_variables(r, w.extract_variables())
AttributeError: 'module' object has no attribute 'expand_variables'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 122, in on_activated
    self.run_linter(view)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 347, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 86, in execute
    worker = cls.hire(cls)
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 31, in hire
    raw_interpreter = get_interpreter(active_view())
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 349, in get_interpreter
    return get_settings(view, 'python_interpreter', 'python')
  File "/Users/shinichi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 204, in get_settings
    r = sublime.expand_variables(r, w.extract_variables())
AttributeError: 'module' object has no attribute 'expand_variables'
```

**Comment by DamnWidget** [comment]
Update your ST3 please, there is no reason at all to being using an
outdated version
