### ISSUE TITLE
IndexError: list index out of range on ST3 and slow/buggy autocomplete

### ISSUE THREAD

**Issue by adrn** [DamnWidget/anaconda#532]
I'm seeing the same behavior as in #306 : 

```
ERROR:root:list index out of range
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/Users/adrian/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 104, in process_message
ERROR:root:    callback(data)
ERROR:root:  File "/Users/adrian/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/signatures.py", line 100, in prepare_data_status
ERROR:root:    self.signature = self.signature.splitlines()[2]
ERROR:root:IndexError: list index out of range
```

At the same time that the error is thrown, the autocomplete popup will appear and refresh repeatedly (glitch) next to my cursor position. This makes it extremely irritating to try to use the autocomplete.

**Comment by DamnWidget** [comment]
Make sure that you are not using SublimeJedi and Anaconda at the same time.

If you're not using them at the same time, paste the anaconda jsonserver logs into a gist and share it please.

**Comment by DamnWidget** [comment]
Any update here?

**Comment by adrn** [comment]
I can't find the jsonserver logs -- any idea where those might be on OSX?

**Comment by adrn** [comment]
(`find ~ -iname "jsonserver"` returned nothing)

**Comment by DamnWidget** [comment]
You can find them in [this section](https://github.com/DamnWidget/anaconda#anaconda-behaves-slowly-and-jsonserver-crashes) of the README

**Comment by adrn** [comment]
Thanks -- here's the full log: https://gist.github.com/adrn/18bb2a5ca0667d3d870c05e8f3d306ba

**Comment by DamnWidget** [comment]
I see nothing weird in the logs, did you try to remove the ST3 cache?

**Comment by adrn** [comment]
I'll give that a try -- is this the only relevant path? 
`~/Library/Application\ Support/Sublime\ Text\ 3/Cache/`

**Comment by DamnWidget** [comment]
I think so but take a look at `~/Library/Application\ Support` as well

**Comment by adrn** [comment]
(I deleted the cache and am just waiting a day to see how things go)

**Comment by adrn** [comment]
That doesn't seem to have worked. I've uploaded a screencast of the error happening and the triggered console Errors:
https://www.youtube.com/watch?v=i5zOs-LNN0E

**Comment by DamnWidget** [comment]
Anaconda should not try to  fire auto completion at all when you type the colon symbol (if you didn't configured your ST3 to fire auto completion on colon for Python code). Are you sure that you don't have any other completion plugin active that is interfering with anaconda? A typical suspect is SublimeCodeIntel that is known for interfere with other completion plugins.

The problem that you show me in the video should never happen in a typical use, anyway, even if you get errors about the signatures you should not feel any "slowness" on the completion due the fact that show signatures and completions are two independent and isolated anaconda asynchronous calls that should not interfere with your typing or with the speed of your ST3.

Please, disable any other plugin in your ST3 and try again, make sure that you are not trying to fire the completion when you type the colon in Python code. As a rule of thumb is always a good idea to disable any other plugin and try to reproduce the problem.

P.S: Restart your ST3 instance after disable plugins and delete the cache as well

**Comment by adrn** [comment]
It's not the semicolon that triggers it -- if I had just gone to a newline, the autocomplete window would still appear. I don't have any other autocomplete plugins installed, to my knowledge. These are the packages I have installed:

"Anaconda",
"AutoWrap",
"Base16 Color Schemes",
"Cython",
"Evernote",
"GitGutter",
"LaTeXTools",
"Markdown Preview",
"MinimalFortran",
"Package Control",
"Python 3",
"RestructuredText Improved",
"SublimeLinter",
"SublimeLinter-pep8",
"SublimeLinter-pyflakes",
"Theme - Flatland",
"Wrap Plus"

I'll try disabling everything else and see what happens.

**Comment by DamnWidget** [comment]
Well, I don't know what is it but something is firing ST3 auto-completion and it is not anaconda, anaconda doesn't ever fires autocompletion by himself, it rather hooks himself into regular ST3 autocompletion event that is normally triggered by ST3 itself.

**Comment by adrn** [comment]
OK I think I have some more info. It doesn't appear to be an extra firing / triggering of auto-complete, but rather a lag in the appearance of the autocomplete popup. Here's [another video that probably explains it better](https://www.youtube.com/watch?v=RUQw8XkJDz8).

**Comment by DamnWidget** [comment]
Do you have any errors at all in your ST3 console? That is a ST3 regular completion popup it does not appears to be enrich with anaconda auto completion.

**Comment by adrn** [comment]
The only error I get is the one I copied in the original issue message. I can't figure this one out. However, this issue is related to Anaconda. If I disable Anaconda, the autocomplete works normally and doesn't lag as it does in the video I posted in the previous comment.
