### ISSUE TITLE
ImportError: No module named 'Default.history_list' 

### ISSUE THREAD

**Issue by ClericPy** [DamnWidget/anaconda#576]
## Expected Behaviour
show definition of functions
## Actual Behaviour
nothing to show
## Steps to Reproduce
Not any more, still occur
## ST3, Anaconda and OS versions
latest , 2.1.5
linux-mint, win10
## ST3 Console Logs
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/ld/.config/sublime-text-3/Packages/Anaconda/anaconda.py", line 17, in <module>
    from .commands import *
  File "/home/ld/.config/sublime-text-3/Packages/Anaconda/commands/__init__.py", line 10, in <module>
    from .find_usages import AnacondaFindUsages
  File "/home/ld/.config/sublime-text-3/Packages/Anaconda/commands/find_usages.py", line 9, in <module>
    from ..anaconda_lib.explore_panel import ExplorerPanel
  File "/home/ld/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/explore_panel.py", line 8, in <module>
    from Default.history_list import get_jump_history_for_view
ImportError: No module named 'Default.history_list'
```
## Anaconda's JsonServer Logs
not received/update recently

## Temporary solution
modify the file : 
```
./sublime-text-3/Packages/Anaconda/anaconda_lib/explore_panel.py
```
remove 2 lines from this file:
```
#from Default.history_list import get_jump_history_for_view
#get_jump_history_for_view(self.view).push_selection(self.view)
```

## PS:
Is there a 'return/go back' command for goto_definition?

**Comment by DamnWidget** [comment]
Hi, seems like you need to update your ST3 version, yes, there is, just use Alt+-

Update ST3 and feel free to close this issue if that solved your problem.

**Comment by ClericPy** [comment]
thank a lot for your reply, I found the error file... 'Default.sublime-package' in the folder 'Installed Packages'...delete that file then everything works well...

and for my go_back requests...Alt + - works quite amazing...
Happy Halloween..
