### ISSUE TITLE
Autocomplete for OpenCV

### ISSUE THREAD

**Issue by TheMikeyR** [DamnWidget/anaconda#578]
I want to make OpenCV autocompletion work with the anaconda plugin, I've been googling the web empty without being able to succeed in the quest of autocompletion. 
Anaconda plugin works fine with stuff like os package etc. but when I'm trying to make it work with opencv I seem to fail.

Been trying to add 
```
    "extra_paths":
    [
        "/home/mikeyr/anaconda2/pkgs/opencv3-3.1.0-py27_0/lib/python2.7/site-packages/"
    ],
```

Where my cv2.so file is located, I'm running Opencv 3.1 with anaconda and python 2.7. When doing locate cv2.so; 
```
/home/mikeyr/anaconda2/lib/python2.7/site-packages/cv2.so
/home/mikeyr/anaconda2/pkgs/opencv-2.4.11-nppy27_0/lib/python2.7/site-packages/cv2.so
/home/mikeyr/anaconda2/pkgs/opencv3-3.1.0-py27_0/lib/python2.7/site-packages/cv2.so
/home/mikeyr/opencv/opencv-2.4.13/build/lib/cv2.so
/usr/local/lib/python2.7/site-packages/cv2.so
```

Been trying multiple paths in the extra_paths setting, without any succes. I hope you guys can help me getting it to work.

## ST3, Anaconda and OS versions
ST3, Build 3114
Ubuntu 16.04
[logs.zip](https://github.com/DamnWidget/anaconda/files/568729/logs.zip)

**Comment by DamnWidget** [comment]
I understand that you are using the anaconda Python distribution. Can you paste your `python_interpreter` configuration?

**Comment by TheMikeyR** [comment]
@DamnWidget I guess you mean my setting in Anaconda.sublime-settings? 
Then it is:
`"python_interpreter": "python",`

**Comment by DamnWidget** [comment]
Just cd to `~/.config/sublime-text-3/Packages/Anaconda/anaconda_lib` in your terminal and then run:
```
python -c "import jedi; print(jedi.Script('import cv2; cv2.').completions());"
```

If you get a result like:
```python
[<Completion: cv2>, <Completion: os>, <Completion: sys>, <Completion: __doc__>, <Completion: __file__>, <Completion: __name__>, <Completion: __package__>]
```
then that means that anaconda should work with your current configuration.

Anyway, I found that Jedi, the library that we use to offer auto-completions has some kind of problem with cv2 and it crashes at some levels. There is an open ticket in https://github.com/davidhalter/jedi/issues/777

**Comment by TheMikeyR** [comment]
@DamnWidget 
Yea I get the exact same error as you listed in [davidhalter/jedi#777](https://github.com/davidhalter/jedi/issues/777)

```
$ python -c "import jedi; print(jedi.Script('import cv2; cv2.').completions());"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "jedi/api/__init__.py", line 169, in completions
    completions = completion.completions()
  File "jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "jedi/api/completion.py", line 164, in _get_context_completions
    completion_names += self._trailer_completions(atom_expr)
  File "jedi/api/completion.py", line 210, in _trailer_completions
    names, self._module.get_statement_for_position(self._position)
  File "jedi/evaluate/finder.py", line 78, in filter_definition_names
    if filter_private_variable(scope, origin):
  File "jedi/evaluate/finder.py", line 621, in filter_private_variable
    instance = scope.get_parent_scope()
AttributeError: 'NoneType' object has no attribute 'get_parent_scope'

I guess I just need to be patient for the issue to be fixed.
```

**Comment by DamnWidget** [comment]
Waiting for fix in Jedi
