### ISSUE TITLE
 [Errno 9] Bad file descriptor with vagrant python interpreter

### ISSUE THREAD

**Issue by kiddick** [DamnWidget/anaconda#588]
I am trying to use similar settings for my vagrant python:

```
Vagrant.configure(2) do |config|
    config.vm.box = "precise64"
    config.vm.network :forwarded_port, guest: 19360, host: 19360
    config.vm.synced_folder = '~/Library/Application Support/Sublime Text 3/Packages/Anaconda', '/anaconda'
end
```

But as a result getting this (at sublime console):

```
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/home/rgrinyov/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 298, in inner_loop
ERROR:root:    poll()
ERROR:root:  File "/home/rgrinyov/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 275, in poll
ERROR:root:    handler.send()
ERROR:root:  File "/home/rgrinyov/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 132, in send
ERROR:root:    sent = self.sock.send(self.outbuffer)
ERROR:root:OSError: [Errno 9] Bad file descriptor

```

Any ideas?

**Comment by DamnWidget** [comment]
What is your `python_interpreter`?

**Comment by kiddick** [comment]
```
"python_interpreter": "vagrant://default:19360?network=forwarded
```

**Comment by DamnWidget** [comment]
The weird part is that the error your OSX is giving you is "Bad file descriptor", it is like the socket was open readonly and you are trying to write on it but that does not have any sense.

Is the problem consistent? You can reproduce it every time that you try or you get this just some times?

**Comment by kiddick** [comment]
Sorry for confusing. I just copy-pasted it from docs. In my settings it is linux style string: 
```
config.vm.synced_folder '~/.config/sublime-text-3/Packages/Anaconda', '/anaconda'
```

So I am using Ubuntu 16.10 as host machine and box with centos 6 as guest mashine.

**Comment by DamnWidget** [comment]
I see.
Do you get that error everytime that you start your ST3 or just in occasions?
Is anaconda working using a local `python_interpreter`?

**Comment by kiddick** [comment]
Errors only with vagrant settings. With local everything is fine.

**Comment by kiddick** [comment]
Does this mapping `&pathmap=/home/user/projects/myproject,/MyProject` work with `tcp` connection to minjson server?

**Comment by DamnWidget** [comment]
Yes it should, the vagrant interpreter just add some additional functionality in top of regular TCP remote workers (like start the VM or start the minserver.py in the VM if is not already running).

**Comment by kiddick** [comment]
I was able to run remote interpreter using this workaround: https://github.com/DamnWidget/anaconda/issues/539#issuecomment-247260624
But unfortunately mapping doesn't work correctly.

**Comment by DamnWidget** [comment]
What you mean with "mapping doesn't work correctly"?

**Comment by kiddick** [comment]
I am getting following errors (when trying to `go to`):
```FileNotFoundError: [Errno 2] No such file or directory: '/path/on/vagrant/machine/to/file.py'````

Ii should be local path instead...

**Comment by DamnWidget** [comment]
Ok, do the following:

* Open ST3 console and write
* `from Anaconda.anaconda_lib.workers.Market import Market`
* `print(Market)`
* The command above will show you a list of workers in your market, write down the Window ID of your worker
* `w = Market().get(<the_window_id_you_wrote_down>)`
* `print(w.interpreter)`
* `print(w.interpreter.pathmap)`

Paste here the results please

**Comment by kiddick** [comment]
```
>>> from Anaconda.anaconda_lib.workers.Market import Market
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'Anaconda.anaconda_lib.workers.Market'
```

**Comment by kiddick** [comment]
I am getting error on this step:
```
print(w.interpreter)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/workers/interpreter.py", line 251, in __repr__
    rep + k + ': ' + v + '\n'
TypeError: Can't convert 'dict' object to str implicitly
```

**Comment by kiddick** [comment]
I've added temporary attribute to figure out what is going on:

```
    def __repr__(self):
        """String representation
        """

        try:
            return ' '.join(self.arguments[0])
        except TypeError:
            rep = ''
            self.dump = self.__data
            for k, v in self.__data.items():
                rep + k + ': ' + v + '\n'
            return rep
```

And in ST3 console:
```
>>> w.interpreter.dump
{'port': '8080', 'pathmap': {'/home/me/myprj': '/home/vagrant/myprj'}, 'scheme': 'tcp', 'host': '127.0.0.1'}
```

**Comment by DamnWidget** [comment]
Looks like the code to handle the mappings when data come from the workers is gone (or it was never commit), that is why Goto does not works.

`commands/goto.py` line 46 should check for active interpreter maps if the interpreter is remote and replace the paths accordingly. I will look into it when I have some time.

**Comment by kiddick** [comment]
Seems it is ok now!

**Comment by DamnWidget** [comment]
You don't get the bad file descriptor error anymore?
