### ISSUE TITLE
A lot of ERROR:root:KeyError: 'result' errors

### ISSUE THREAD

**Issue by kiddick** [DamnWidget/anaconda#590]
In many cases of using `anaconda_goto` commands in ST3 log I am getting:
```
ERROR:root:KeyError: 'result'
ERROR:root:'result'
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 104, in process_message
ERROR:root:    callback(data)
ERROR:root:  File "/home/me/.config/sublime-text-3/Packages/Anaconda/commands/goto.py", line 37, in on_success
ERROR:root:    if not data['result']:
ERROR:root:KeyError: 'result'
```

Though default command `goto_definition` works well.

**Comment by DamnWidget** [comment]
Can you please provide the contents of your JsonServer logs? (https://github.com/DamnWidget/anaconda/blob/master/.github/ISSUE_TEMPLATE.md#anacondas-jsonserver-logs) 

P.S: The ISSUE_TEMPLATE is there for a reason btw

**Comment by kiddick** [comment]
```
2016-11-22 19:29:58,081: INFO    : client requests: goto
2016-11-22 19:29:58,291: ERROR   : 'NoneType' object is not iterable
2016-11-22 19:29:58,291: ERROR   : Traceback (most recent call last):
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py", line 104, in found_terminator
    self.handle_command(handler_type, method, uid, vid, data)
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py", line 131, in handle_command
    handler(method, data, uid, vid, self.return_back, DEBUG_MODE).run()
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 30, in run
    super(JediHandler, self).run()
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_server/lib/anaconda_handler.py", line 48, in run
    command(**kwargs)
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 87, in goto
    Goto(self.callback, self.uid, self.script)
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_server/commands/goto.py", line 14, in __init__
    super(Goto, self).__init__(callback, uid)
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_server/commands/base.py", line 14, in __init__
    self.run()
  File "/home/me/.config/sublime-text-3/Packages/Anaconda/anaconda_server/commands/goto.py", line 38, in run
    {'success': success, 'result': list(data), 'uid': self.uid})
TypeError: 'NoneType' object is not iterable

2016-11-22 19:29:58,291: INFO    : About push back to ST3: {"vid": null, "uid": "7b7e7d14bb584a978757cb47bf69b9fb", "success": false, "error": "'NoneType' object is not iterable"}
```

**Comment by DamnWidget** [comment]
Resolved, waiting for release

**Comment by DamnWidget** [comment]
Please, confirm that the fix is actually working in your case, feel free to re-open if not.

**Comment by kiddick** [comment]
Should I manually update up to 2.1.8 or just wait for release on packagecontrol.io ?

**Comment by DamnWidget** [comment]
Don't bother with updating manually, just wait until Package Control gets aware of the new version.
