### ISSUE TITLE
Jump to definition raises KeyError every time

### ISSUE THREAD

**Issue by kissgyorgy** [DamnWidget/anaconda#597]
## Expected Behaviour
Jump to object definition or module

## Actual Behaviour
Nothing happens, just errors in logs

## Steps to Reproduce
I uninstalled and reinstalled Anaconda, deleted cache, logs, indexes, even custom configuration.
Press `CTRL + SHIFT + G` on a Python module or object.

## ST3, Anaconda and OS versions
ST3: dev 3125
Anaconda: 2.1.11 (probably?)
OS X: 10.11.6 (El Capitan)

## ST3 Console Logs
```
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 104, in process_message
ERROR:root:    callback(data)
ERROR:root:  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/commands/goto.py", line 39, in on_success
ERROR:root:    if not data['result']:
ERROR:root:KeyError: 'result'
```
## Anaconda's JsonServer Logs
```
2016-12-09 13:16:16,491: INFO    : client requests: lint
2016-12-09 13:16:16,504: ERROR   : '>' not supported between instances of 'int' and 'list'
2016-12-09 13:16:16,504: DEBUG   : ['Traceback (most recent call last):', '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/commands/pep8.py", line 31, in run', '    self.settings, self.code, self.filename),', '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/anaconda_pep8.py", line 56, in lint', "    code, filename, settings.get('pep8_rcfile'), **check_params", '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/anaconda_pep8.py", line 121, in check', '    pep8.Checker(filename, good_lines, options=options).check_all()', '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/autopep/../linting/pycodestyle.py", line 1714, in check_all', '    for token in self.generate_tokens():', '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/autopep/../linting/pycodestyle.py", line 1665, in generate_tokens', '    self.maybe_check_physical(token)', '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/autopep/../linting/pycodestyle.py", line 1675, in maybe_check_physical', '    self.check_physical(token[4])', '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/autopep/../linting/pycodestyle.py", line 1569, in check_physical', '    result = self.run_check(check, argument_names)', '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/autopep/../linting/pycodestyle.py", line 1557, in run_check', '    return check(*arguments)', '  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/autopep/../linting/pycodestyle.py", line 216, in maximum_line_length', '    if length > max_line_length and not noqa:', "TypeError: '>' not supported between instances of 'int' and 'list'"]
2016-12-09 13:16:16,505: INFO    : About push back to ST3: b'{"success": true, "errors": [{"underline_range": false, "level": "W", "lineno": 9, "message": "%r imported but unused", "raw_error": "\'logging\' imported but unused", "offset": 0, "regex": "(^|\\\\s+|,\\\\s*|as\\\\s+)(?P<underline>[\\\\w]*logging[\\\\w]*)", "linematch": "(from\\\\s+[\\\\w_\\\\.]+\\\\s+)?import\\\\s+(?P<match>[^#;]+)"}], "uid": "1d074352462342e19d18fbe69247aca3", "vid": 19}\r\n'
2016-12-09 13:16:18,606: INFO    : client requests: goto
2016-12-09 13:16:18,607: ERROR   : [Errno 2] No such file or directory: '/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/grammar3.6.txt'
2016-12-09 13:16:18,608: ERROR   : Traceback (most recent call last):
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/__init__.py", line 56, in load_grammar
    return _loaded_grammars[path]
KeyError: '/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/grammar3.6.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 104, in found_terminator
    self.handle_command(handler_type, method, uid, vid, data)
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 131, in handle_command
    handler(method, data, uid, vid, self.return_back, DEBUG_MODE).run()
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 30, in run
    super(JediHandler, self).run()
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/lib/anaconda_handler.py", line 48, in run
    command(**kwargs)
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 87, in goto
    Goto(self.callback, self.uid, self.script)
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 47, in script
    return self.jedi_script(**self.data)
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 54, in jedi_script
    return jedi.Script(source, int(line), int(offset), filename, encoding)
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/api/__init__.py", line 126, in __init__
    self._grammar = load_grammar(version='%s.%s' % sys.version_info[:2])
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/__init__.py", line 58, in load_grammar
    return _loaded_grammars.setdefault(path, generate_grammar(path))
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/pgen2/pgen.py", line 393, in generate_grammar
    p = ParserGenerator(filename)
  File "/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/pgen2/pgen.py", line 18, in __init__
    stream = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/grammar3.6.txt'

2016-12-09 13:16:18,608: INFO    : About push back to ST3: b'{"success": false, "uid": "6a30334639044f2598206dcfd24034b5", "vid": null, "error": "[Errno 2] No such file or directory: \'/Users/walkman/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/parser/grammar3.6.txt\'"}\r\n'
```

**Comment by DamnWidget** [comment]
Even that anaconda should gracefully failing on this, the problem is that Jedi does not supports Python 2.6 grammars yet and you are using a Python 3.6 interpreter. Even if I add some `try` block or use `get` in the dictionary object (that I should) you are never gonna make lot of functionality offered by Jedi to work, not unless Python 3.6 grammars are added to the library.

**Comment by kissgyorgy** [comment]
I did not realized it's because of 3.6 :D thanks
