### ISSUE TITLE
[Errno 9] Bad file descriptor (with Docker integration)

### ISSUE THREAD

**Issue by deepjedi** [DamnWidget/anaconda#626]
## Expected Behaviour
Instantiate a Docker container and be able to link to the python_interpreter inside the running Docker container

## Actual Behaviour
While the Docker container runs fine, ST3 is not able to link to the python_interpreter, giving an error

## Steps to Reproduce
Run the following command to instantiate a Docker container

docker run -d --rm -v /home/deepjedi/.config/sublime-text-3/Packages/Anaconda:/opt/anaconda -v /home/deepjedi/dev/prj/test:/test -p 9998:9998 python:3.6 /opt/anaconda/anaconda_server/docker/start python 19360 test

Inside test.sublime-project,

{
    "settings":
    {
        "python_interpreter": "tcp://localhost:9998?pathmap=/home/deepjedi/dev/prj/test,/test"
    }
}

## ST3, Anaconda and OS versions
ST3 Build 3126, Anaconda (not sure how to check the version but downloaded it in March 2017), Ubuntu 16.04

## ST3 Console Logs
ERROR:root:Unhandled exception in poll, restarting the poll request
ERROR:root:[Errno 9] Bad file descriptor
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/home/deepjedi/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 298, in inner_loop
ERROR:root:    poll()
ERROR:root:  File "/home/deepjedi/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 275, in poll
ERROR:root:    handler.send()
ERROR:root:  File "/home/deepjedi/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 132, in send
ERROR:root:    sent = self.sock.send(self.outbuffer)
ERROR:root:OSError: [Errno 9] Bad file descriptor

## Anaconda's JsonServer Logs
2017-03-09 15:16:00,583: INFO    : client requests: lint
2017-03-09 15:16:00,589: INFO    : About push back to ST3: {"vid": 78, "errors": [{"level": "V", "raw_error": "[V] PEP 8 (W292): no newline at end of file", "lineno": 17, "offset": 13, "message": "[v] pep 8 (%s): %s", "underline_range": true}], "uid": "03e1230fee084c179566d0b1bba9ab3e", "success": true}

2017-03-09 15:16:22,348: INFO    : client requests: lint
2017-03-09 15:16:22,353: INFO    : About push back to ST3: {"vid": 78, "errors": [{"level": "V", "raw_error": "[V] PEP 8 (W292): no newline at end of file", "lineno": 17, "offset": 13, "message": "[v] pep 8 (%s): %s", "underline_range": true}], "uid": "27a3bc4aeb4e48b191684b8ade1e8db4", "success": true}

2017-03-09 15:17:26,796: INFO    : client requests: lint
2017-03-09 15:17:26,806: INFO    : About push back to ST3: {"vid": 78, "errors": [{"level": "V", "raw_error": "[V] PEP 8 (W292): no newline at end of file", "lineno": 17, "offset": 13, "message": "[v] pep 8 (%s): %s", "underline_range": true}], "uid": "0a83c99e9e3e4353912233336f5e262a", "success": true}

## Note
The Console logs above are from 2017-03-10.  There seem to be no logs from 2017-03-10 in JsonServer Logs.

**Comment by DamnWidget** [comment]
Hi 
What happens if you connect with `curl`, `nc` or `httpie` directly into your `localhost:9998` because I don't see how the port `19360` that you are binding your `jsonserver` instance into your container is exposed to the host.

**Comment by deepjedi** [comment]
deepjedi@TuringBook:~$ curl localhost:9998
curl: (56) Recv failure: Connection reset by peer
deepjedi@TuringBook:~$ curl localhost:19360
curl: (7) Failed to connect to localhost port 19360: Connection refused

**Comment by DamnWidget** [comment]
Expose the port `19360` instead, I think there is probably a typo in the wiki examples

**Comment by deepjedi** [comment]
Okay, this seems to be the fix, indeed just a typo after all.  I'm just not savvy enough to spot and resolve such issues myself.  Thanks a lot!

**Comment by DamnWidget** [comment]
No problem I will fix the wiki examples
