### ISSUE TITLE
Autoformatting failing on line continuation

### ISSUE THREAD

**Issue by stewit** [DamnWidget/anaconda#690]
## Expected Behaviour
autoformat should not fail on files with line continuation content as in
```
a = ["a",
 "b"]
```
## Actual Behaviour
Statusbar shows: "Autoformatting failed, buffer not changed" and nothing is autoformatted.
## Steps to Reproduce
Save file with content above and press autoformat key combinaton. 

For me the problem occurs after update to 2.1.20. Completely uneducated guess: Has something to do with fix introduced for https://github.com/DamnWidget/anaconda/issues/680

## ST3, Anaconda and OS versions
ST3: Stable, Build 3126
Anaconda: 2.1.20
OS: Archlinux
## Anaconda's JsonServer Logs
2017-08-14 13:46:26,923: ERROR   : invalid literal for int() with base 10: 'continuation'
2017-08-14 13:46:26,923: DEBUG   : ['Traceback (most recent call last):', '  File "/home/steffen/.config/sublime-text-3/Packages/Anaconda/anaconda_server/commands/autoformat.py", line 38, in run', '    self.code.splitlines(), options=self.options),', '  File "/home/steffen/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/autopep/autopep8_lib/autopep8.py", line 3149, in fix_lines', '    fixed_source = fix.fix()', '  File "/home/steffen/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/autopep/autopep8_lib/autopep8.py", line 569, in fix', '    aggressive=self.options.aggressive))', '  File "/home/steffen/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/autopep/autopep8_lib/autopep8.py", line 512, in _fix_source', '    modified_lines = fix(result)', '  File "/home/steffen/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/autopep/autopep8_lib/autopep8.py", line 585, in _fix_reindent', "    num_indent_spaces = int(result['info'].split()[1])", "ValueError: invalid literal for int() with base 10: 'continuation'"]
2017-08-14 13:46:26,923: INFO    : About push back to ST3: b'{"success": false, "error": "invalid literal for int() with base 10: \'continuation\'", "uid": "7cc9db8e6e5b4c5a837d9d66fbab0fc4", "vid": 51}\r\n'

**Comment by DamnWidget** [comment]
Yeah, looks like `continuation` is not a valid base 10 integer

**Comment by MerreM** [comment]
Also seeing this.

**Comment by MerreM** [comment]
Replaced my autopep8.py in 
~/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/autopep/autopep8_lib

with the one from here...

https://pypi.python.org/packages/0a/fc/c541b2fa1b244e0484216076b95468dc011ae90016b8f37333a24a11e468/autopep8-1.3.2.tar.gz#md5=5aa2ab9ff4ac0f9ac143229f7c3fed7b

Working again, but largely untested.

**Comment by DamnWidget** [comment]
Then you probably don't get any message information in the linter for the following error codes:
- E124
- E128
- E123
- E122
- E127
- E131
- E126
- E121

**Comment by DamnWidget** [comment]
This should be working again, please, confirm and close.

**Comment by stewit** [comment]
Works! Thanks.
