### ISSUE TITLE
Anaconda not working in ST3 on Windows 10

### ISSUE THREAD

**Issue by cschweiger** [DamnWidget/anaconda#736]
## Expected Behaviour
Full Anaconda package functionality

## Actual Behaviour
No Anaconda package functionality (linting, code completion, etc.)

## Steps to Reproduce
* Python (via Anaconda3 distribution) installed at C:\Users\cschweiger\anaconda3
* ST3 installed at C:\Program Files\Sublime Text 3
Create project directory at C:\Users\cschweiger\Projects\repos\dev\test
Create conda environment at C:\Users\cschweiger\Projects\envs\test
Create ST3 project file at C:\Users\cschweiger\Projects\repos\dev\test\config\win as:
```json
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"C:/Users/cschweiger/Projects/envs/test/python.exe\" -u \"$file\"",
			"word_wrap": false,
		}
	],
	"folders":
	[
		{
			"path": "../..",
			"folder_exclude_patterns": ["tmp", "log", ".*", "__pycache__"],
			"file_exclude_patterns": ["desktop.ini"]
		}
	],
	"settings":
	{
		"python_interpreter": "\"C:/Users/cschweiger/Projects/envs/test/python.exe\""
	}
}
```

Open ST3, create a .py file, and run it.  Said file will run without error, using the correct environment executable, despite the console output below.

## ST3, Anaconda and OS versions
ST3: 3.0, build 3143 / Anaconda: v2.1.25 / OS: Windows 10

## ST3 Console Logs
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/cschweiger/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/cschweiger/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/cschweiger/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
"Packages/Color Scheme - Default/Solarized (Dark).tmTheme" is no longer maintained and is now part of "Color Scheme - Legacy"
pre session restore time: 0.134911
startup time: 0.197911
first paint time: 0.199911
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin Function Name Display.FunctionNameStatus
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin Indent XML.indentxml
reloading plugin Indent XML.setup
reloading plugin Logging Control.logging_control
reloading plugin LoremIpsum.LoremIpsum
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin Python Breakpoints.PythonBreakpoints
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Solarized Toggle.SolarizedToggle
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin Terminal.Terminal
plugins loaded
Resetting logging system...
17:16:16 INFO  Logging Control.logging_control:266 reset_logging_system() Logging system has been reset; root level is INFO; console level is DEBUG; logging to file is DISABLED
Package Control: Skipping automatic upgrade, last run at 2018-01-15 17:05:07, next run at 2018-01-15 18:05:07 or after
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\listeners\linting.py", line 82, in on_load
    self.run_linter(view)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\linting\sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 75, in _start_worker
    wk.start()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 50, in start
    self._update_python_builder()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 96, in _update_python_builder
    self.interpreter.python
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "C:\Program Files\Sublime Text 3\sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\listeners\linting.py", line 124, in on_activated
    self.run_linter(view)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\linting\sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 75, in _start_worker
    wk.start()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 50, in start
    self._update_python_builder()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 96, in _update_python_builder
    self.interpreter.python
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "C:\Program Files\Sublime Text 3\sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\listeners\linting.py", line 124, in on_activated
    self.run_linter(view)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\linting\sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 75, in _start_worker
    wk.start()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 50, in start
    self._update_python_builder()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 96, in _update_python_builder
    self.interpreter.python
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "C:\Program Files\Sublime Text 3\sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
Traceback (most recent call last):
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\listeners\linting.py", line 50, in <lambda>
    sublime.set_timeout(lambda: self.lint(), int(delay * 1000))
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\listeners\linting.py", line 47, in lint
    self.run_linter(view)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\linting\sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 75, in _start_worker
    wk.start()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 50, in start
    self._update_python_builder()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 96, in _update_python_builder
    self.interpreter.python
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "C:\Program Files\Sublime Text 3\sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\listeners\linting.py", line 124, in on_activated
    self.run_linter(view)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\linting\sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\market.py", line 75, in _start_worker
    wk.start()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 50, in start
    self._update_python_builder()
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\workers\local_worker.py", line 96, in _update_python_builder
    self.interpreter.python
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "C:\Users\cschweiger\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\builder\python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "C:\Program Files\Sublime Text 3\sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22

## Anaconda's JsonServer Logs
There is no anaconda_jsonserver.log file at C:\Users\cschweiger\AppData\Roaming\Anaconda\Logs\test.

I've also tried changing the debug settings in the Anaconda user settings file, closed ST3, manually started the json server and I get no debug output there; only the following:
DEBUG:root:bind: address=('localhost', 9999)
DEBUG:root:listen: backlog=5
INFO:root:Anaconda Server started in 9999 for PID DEBUG with cache dir C:\Users\cschweiger\AppData\Roaming\Jedi\Jedi\test
INFO:root:Anaconda Server started in DEBUG mode...
DEBUG MODE

And after that, zero output whatsoever.  

And taking yet another stab at troubleshooting, I've tried just creating a .py file with no ST3 project association, and everything works as expected (linting, code completion, etc.).  So I can only figure that I've either got a problem with 1) how I'm setting up my project file for ST3 to work with Anaconda or 2) my conda environment; or of course some combination of the two.  Any help would be greatly appreciated!

**Comment by DamnWidget** [comment]
Try with this `python_interpreter` path:
`"C:\\\\Users\\cschweiger\\Projects\\envs\\tes\\/python.exe"`

**Comment by cschweiger** [comment]
Thanks for the quick reply; that worked.  Not sure how I wound up using an escape pattern for a Windows path that worked for ST3/Python itself but not Anaconda.  Kind of an interesting edge case, but your solution did the trick.  Might be worth adding a Windows project file example to your (excellent) [configuration instructions](http://damnwidget.github.io/anaconda/anaconda_settings/)?  Thanks again for the assistance and for developing such a great plugin.
