### ISSUE TITLE
Setting "python_interpreter" has no effect when running test

### ISSUE THREAD

**Issue by bogdanbolchis** [DamnWidget/anaconda#739]
## Expected Behaviour
Python tests running and passing/failing
## Actual Behaviour
```
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/site-packages/_pytest/config.py", line 373, in _importconftest
      mod = conftestpath.pyimport()
    File "/usr/local/lib/python2.7/site-packages/py/_path/local.py", line 662, in pyimport
      __import__(modname)
    File "[redacted]/tests/conftest.py", line 216
  SyntaxError: Non-ASCII character '\xe2' in file [redacted]/tests/conftest.py on line 216, but no encoding declared; see http://python.org/dev/peps/pep-  0263/ for details
  ERROR: could not load [redacted]/tests/conftest.py
```

## Steps to Reproduce
Update project settings to: 

```
"settings":
	{
		"python_interpreter": "/usr/local/bin/python3.6"
	}
```
## ST3, Anaconda and OS versions
ST3 (3143), Anaconda 2.1.25, macOS 10.12.6 (16G1114)

## ST3 Console Logs
```
tests.reducers.test_ui.py
['which python && py.test -sv', '', '']
Running which python && py.test -sv  
reloading settings Packages/User/PythonTestRunner.last-run
```
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
[anaconda_jsonserver.log](https://github.com/DamnWidget/anaconda/files/1667968/anaconda_jsonserver.log)

* Windows: %APPDATA\\Anaconda\\Logs

**Comment by bogdanbolchis** [comment]
I managed to make it work by using this in Anaconda.sublime-settings:

```
{
    "test_command": "tox -e py36",
}
```

However, running a specific test (e.g. the one under the cursor) is not possible for me with the current set of options.
