### ISSUE TITLE
Linting exception thrown when encountering Python 3.6 variable type annotation

### ISSUE THREAD

**Issue by a-musing-moose** [DamnWidget/anaconda#746]
## Expected Behaviour

The linting should complete correctly

## Actual Behaviour

Raises the following exception

```
Traceback (most recent call last):
  File "/opt/anaconda/anaconda_server/commands/pyflakes.py", line 31, in run
    self.settings, self.code, self.filename),
  File "/opt/anaconda/anaconda_lib/linting/anaconda_pyflakes.py", line 44, in lint
    errors.extend(self.check(code, filename, pyflakes_ignore))
  File "/opt/anaconda/anaconda_lib/linting/anaconda_pyflakes.py", line 67, in check
    w = pyflakes.Checker(tree, filename, ignore)
  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 494, in __init__
    self.handleChildren(tree)
  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 862, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 696, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'ANNASSIGN'
```

## Steps to Reproduce

Add a variable type annotation to a python file. e.g.:

```
from typing import Dict

a_thing: Dict[str, str] = {}
```

## ST3, Anaconda and OS versions

ST3 = 3.0, build 3143
Anaconda = 2.1.25
OS = Linux Ubuntu but I am running the miniserver inside an alpine line Docker container 
Python = 3.6.4

## ST3 Console Logs

Nothing related

## Anaconda's JsonServer Logs

```
anaconda_1  | INFO:root:client requests: lint
anaconda_1  | ERROR:root:'Checker' object has no attribute 'ANNASSIGN'
anaconda_1  | DEBUG:root:['Traceback (most recent call last):', '  File "/opt/anaconda/anaconda_server/commands/pyflakes.py", line 31, in run', '    self.settings, self.code, self.filename),', '  File "/opt/anaconda/anaconda_lib/linting/anaconda_pyflakes.py", line 44, in lint', '    errors.extend(self.check(code, filename, pyflakes_ignore))', '  File "/opt/anaconda/anaconda_lib/linting/anaconda_pyflakes.py", line 67, in check', '    w = pyflakes.Checker(tree, filename, ignore)', '  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 494, in __init__', '    self.handleChildren(tree)', '  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 816, in handleChildren', '    self.handleNode(node, tree)', '  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 862, in handleNode', '    handler = self.getNodeHandler(node.__class__)', '  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 696, in getNodeHandler', '    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)', "AttributeError: 'Checker' object has no attribute 'ANNASSIGN'"]
anaconda_1  | 2018-02-15 21:54:22,566: INFO    : client requests: lint
anaconda_1  | 2018-02-15 21:54:22,574: ERROR   : 'Checker' object has no attribute 'ANNASSIGN'
anaconda_1  | 2018-02-15 21:54:22,575: DEBUG   : ['Traceback (most recent call last):', '  File "/opt/anaconda/anaconda_server/commands/pyflakes.py", line 31, in run', '    self.settings, self.code, self.filename),', '  File "/opt/anaconda/anaconda_lib/linting/anaconda_pyflakes.py", line 44, in lint', '    errors.extend(self.check(code, filename, pyflakes_ignore))', '  File "/opt/anaconda/anaconda_lib/linting/anaconda_pyflakes.py", line 67, in check', '    w = pyflakes.Checker(tree, filename, ignore)', '  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 494, in __init__', '    self.handleChildren(tree)', '  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 816, in handleChildren', '    self.handleNode(node, tree)', '  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 862, in handleNode', '    handler = self.getNodeHandler(node.__class__)', '  File "/opt/anaconda/anaconda_lib/linting/pyflakes/checker.py", line 696, in getNodeHandler', '    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)', "AttributeError: 'Checker' object has no attribute 'ANNASSIGN'"]
anaconda_1  | INFO:root:client requests: lint
anaconda_1  | 2018-02-15 21:54:23,552: INFO    : client requests: lint
```

**Comment by Badg** [comment]
I've been getting this too; basically the same jsonserver logs (and same nothing related in console logs).

+ ST3 = 3.1.1, build 3176
+ Anaconda = 2.1.29
+ OS = OSX Mojave 10.14.3
+ Python = 3.7.1
