### ISSUE TITLE
'mypy.main' has no attribute '__version__'

### ISSUE THREAD

**Issue by dvdmgl** [DamnWidget/anaconda#780]
## Expected Behaviour
To link with mypy, jsonserver working
## Actual Behaviour
jsonserver not working
## Steps to Reproduce
```
pip freeze | grep mypy
mypy==0.620
mypy-lang==0.5.0
```
```
python -B anaconda_server/jsonserver.py -p test 9999 DEBUG
Traceback (most recent call last):
  File "anaconda_server/jsonserver.py", line 33, in <module>
    from handlers import ANACONDA_HANDLERS
  File "/home/dvdmgl/.config/sublime-text-3/Packages/Anaconda/anaconda_server/handlers/__init__.py", line 11, in <module>
    from .python_lint_handler import PythonLintHandler
  File "/home/dvdmgl/.config/sublime-text-3/Packages/Anaconda/anaconda_server/handlers/python_lint_handler.py", line 16, in <module>
    from linting.anaconda_mypy import MyPy as AnacondaMyPy
  File "anaconda_lib/linting/anaconda_mypy.py", line 23, in <module>
    int(i) for i in mypy.__version__.replace('-dev', '').split('.')
AttributeError: module 'mypy.main' has no attribute '__version__'
```
## ST3, Anaconda and OS versions
sublime 3175
anaconda v2.1.29
ubuntu 18.04
## ST3 Console Logs
```
 ...last message repeated one more time in the last 10s
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x7fb7a6cd6210> initial check failed because:

can not connect to /home/dvdmgl/.local/share/anaconda/run/my_proj/anaconda.sock. tried to connect 21 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that the Unix Domain Socket file /home/dvdmgl/.local/share/anaconda/run/my_proj/anaconda.sock exists and that you can connect to it writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(/home/dvdmgl/.local/share/anaconda/run/my_proj/anaconda.sock)

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
```
## Anaconda's JsonServer Logs
```
bind: address=/home/dvdmgl/.local/share/anaconda/run/my_proj/anaconda.sock
2018-04-23 11:21:27,247: DEBUG   : listen: backlog=5
2018-04-23 11:21:27,248: INFO    : Anaconda Server started in /home/dvdmgl/.local/share/anaconda/run/my_proj/anaconda.sock for PID 18022 with cache dir /home/dvdmgl/.cache/jedi/my_proj and extra paths /home/dvdmgl/my_proj
2018-04-23 11:21:27,269: INFO    : Incomming connection from ''
2018-04-23 11:21:27,270: INFO    : Incomming connection from ''
2018-04-23 11:21:27,275: INFO    : client requests: lint
2018-04-23 11:21:27,328: INFO    : client requests: lint
2018-04-23 11:21:32,305: INFO    : client requests: lint
2018-04-23 11:23:18,169: INFO    : client requests: lint
2018-04-23 11:23:18,870: INFO    : client requests: lint
2018-04-23 11:23:21,039: INFO    : client requests: lint
2018-04-23 11:24:56,686: INFO    : client requests: lint
2018-04-23 11:25:17,270: INFO    : client requests: lint
2018-04-23 11:25:31,119: INFO    : client requests: lint
2018-04-23 11:26:51,913: INFO    : client requests: lint
2018-04-23 11:27:08,309: INFO    : client requests: lint
2018-04-23 11:27:10,308: INFO    : client requests: lint
2018-04-23 11:27:10,489: INFO    : client requests: lint
2018-04-23 11:27:34,552: INFO    : client requests: lint
2018-04-23 11:27:37,916: INFO    : client requests: lint
2018-04-23 11:27:37,966: INFO    : client requests: lint
2018-04-23 11:28:33,790: INFO    : client requests: lint
2018-04-23 11:28:41,915: INFO    : client requests: lint
2018-04-23 11:28:42,013: INFO    : client requests: lint
2018-04-23 11:32:14,549: INFO    : client requests: lint
2018-04-23 11:32:38,959: INFO    : process 18022 does not exists stopping server...
2018-04-23 11:32:38,959: INFO    : Closing the socket, server will be shutdown now...
```
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by r-salas** [comment]
This error happens if you have installed `mypy-lang` instead of `mypy`. The solution is to uninstall `mypy-lang`:
```console
$ python3 -m pip uninstall mypy-lang
```
And install the correct package:
```console
$ python3 -m pip install mypy
```
Leaving this in case it happens to someone else.
