### ISSUE TITLE
Sublime Text 3: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by gamesguru** [DamnWidget/anaconda#793]
## The problem

I get an error message box when starting Sublime on macOS.  Autocomplete doesn't seem to work all the way, but things are okay I guess.  Am looking for improvement or some resolution.  Thanks.

It doesn't happen all the time, and no other python instances are running in `ps -e|grep python`.

## ST3 Console Logs
```
$ subl user.py
MyPy is enabled but we could not import it
DEBUG:root:bind: address=('localhost', 55888)
DEBUG:root:listen: backlog=5
INFO:root:Anaconda Server started in 55888 for PID 94155 with cache dir /Users/sjaroch/Library/Caches/Jedi/anaconda-2
INFO:root:Incomming connection from ('127.0.0.1', 55910)
INFO:root:Incomming connection from ('127.0.0.1', 55911)
INFO:root:client requests: lint
{'vid': 14, 'errors': [{'level': 'E', 'raw_error': '[E] invalid syntax', 'lineno': 30, 'offset': 36, 'message': '[e] %s', 'underline_range': True}], 'uid': u'd86ce12c65614b6298e0e30931a028b8', 'success': True}
INFO:root:client requests: lint
{'vid': 14, 'errors': [{'level': 'E', 'raw_error': '[E] invalid syntax', 'lineno': 30, 'offset': 36, 'message': '[e] %s', 'underline_range': True}], 'uid': u'fddff863d0fe49b2b611e53c9f09cba2', 'success': True}
MyPy is enabled but we could not import it
ERROR:root:Traceback (most recent call last):
  File "/Users/sjaroch/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 335, in <module>
    server = JSONServer(('localhost', port))
  File "/Users/sjaroch/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 156, in __init__
    self.bind(self.address)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 342, in bind
    return self.socket.bind(addr)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use

ERROR:root:[Errno 48] Address already in use
Traceback (most recent call last):
  File "/Users/sjaroch/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 357, in <module>
    server.shutdown()
NameError: name 'server' is not defined
2018-10-15 11:26:36.462 Sublime Text[94153:1319877] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9800)
```
## Anaconda's JsonServer Logs

See attached logs, I have not gone through them yet
[anaconda.zip](https://github.com/DamnWidget/anaconda/files/2479396/anaconda.zip)

**Comment by softinio** [comment]
I get this too. Any ideas?

**Comment by gamesguru** [comment]
My Windows drive is now also acting up.  Linux is the lone survivor.  I have the same anaconda settings for each drive.

```
{
    "auto_formatting": true,
    "autoformat_ignore":
    [
        "E309",
        "E501"
    ],
    "pep8_ignore":
    [
        "E309",
        "E501"
    ],
    "auto_formatting_timeout": 5,
    "anaconda_linter_underlines": false,
    "anaconda_linter_mark_style": "none",
    "display_signatures": false,
    "disable_anaconda_completion": false
}
```

**Comment by JollyR0ger42** [comment]
Have same error when trying to start jsonserver manually
When execute:
`python .\anaconda_server\jsonserver.py -p test1 9999 1`
I get this:
`.\anaconda_lib\autopep\../linting\pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
MyPy is enabled but we could not import it
ERROR:root:Traceback (most recent call last):
  File ".\anaconda_server\jsonserver.py", line 337, in <module>
    if not LINUX:
  File ".\anaconda_server\jsonserver.py", line 158, in __init__
    # WSL 1903 fix
TypeError: chmod: path should be string, bytes or os.PathLike, not tuple

ERROR:root:chmod: path should be string, bytes or os.PathLike, not tuple
Traceback (most recent call last):
  File ".\anaconda_server\jsonserver.py", line 337, in <module>
    if not LINUX:
  File ".\anaconda_server\jsonserver.py", line 158, in __init__
    # WSL 1903 fix
TypeError: chmod: path should be string, bytes or os.PathLike, not tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\anaconda_server\jsonserver.py", line 359, in <module>
    logger.error(str(error))
NameError: name 'server' is not defined`

**Comment by karolyi** [comment]
Working on it. Related to #820

**Comment by JollyR0ger42** [comment]
> Working on it. Related to #820
Man, thank you, you are my hero!
