### ISSUE TITLE
Typo in WSL 1903 fix

### ISSUE THREAD

**Issue by digulla** [DamnWidget/anaconda#822]
Starting the jsonserver.py fails with:

```
2019-06-11 11:26:37,355: ERROR   : global name 'address_family' is not defined
2019-06-11 11:26:44,357: ERROR   : Traceback (most recent call last):
  File "/home/swissquant.local/digulla/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py", line 345, in <module>
    server = JSONServer(unix_socket_path.socket)
  File "/home/swissquant.local/digulla/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py", line 157, in __init__
    if address_family == socket.AF_UNIX:
NameError: global name 'address_family' is not defined
```

Fix: Line 157

        if address_family == socket.AF_UNIX:

should read

        if self.address_family == socket.AF_UNIX:

(just like line 153).

## ST3, Anaconda and OS versions
Anaconda v2.1.31

**Comment by idadzie** [comment]
Beat me to it :smile:

**Comment by bicobus** [comment]
Check https://github.com/DamnWidget/anaconda/commit/2830a33c70d4eafcd35e17941f8bca2829f4c443 and #820 

Issue is known and fixed, release just hasn't been made.

**Comment by karolyi** [comment]
should be fixed now with the latest release, let me know when it isn't.
