### ISSUE TITLE
Traceback with 2.1.33

### ISSUE THREAD

**Issue by adudek16** [DamnWidget/anaconda#823]
## Expected Behaviour
No tracebacks

## Actual Behaviour
```
ERROR:root:Unhandled exception in poll, restarting the poll request
ERROR:root:No JSON object could be decoded
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 92, in process_message
ERROR:root:    data = sublime.decode_value(message.decode('utf8'))
ERROR:root:  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 215, in decode_value
ERROR:root:    raise ValueError(err)
ERROR:root:ValueError: Error trying to decode value: Expected value in (data):1:1
ERROR:root:
ERROR:root:During handling of the above exception, another exception occurred:
ERROR:root:
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "./python3.3/json/decoder.py", line 367, in raw_decode
ERROR:root:StopIteration
ERROR:root:
ERROR:root:During handling of the above exception, another exception occurred:
ERROR:root:
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 298, in inner_loop
ERROR:root:    poll()
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 270, in poll
ERROR:root:    handler.recv()
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 187, in recv
ERROR:root:    self.process_message()
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 94, in process_message
ERROR:root:    data = json.loads(message.replace(b'\t', b' ' * 8).decode('utf8'))
ERROR:root:  File "./python3.3/json/__init__.py", line 316, in loads
ERROR:root:  File "./python3.3/json/decoder.py", line 351, in decode
ERROR:root:  File "./python3.3/json/decoder.py", line 369, in raw_decode
ERROR:root:ValueError: No JSON object could be decoded
ERROR:root:Unhandled exception in poll, restarting the poll request
ERROR:root:Expecting ':' delimiter: line 1 column 4099 (char 4098)
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 92, in process_message
ERROR:root:    data = sublime.decode_value(message.decode('utf8'))
ERROR:root:  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 215, in decode_value
ERROR:root:    raise ValueError(err)
ERROR:root:ValueError: Error trying to decode value: Expected ':' in (data):1:4099
ERROR:root:
ERROR:root:During handling of the above exception, another exception occurred:
ERROR:root:
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 298, in inner_loop
ERROR:root:    poll()
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 270, in poll
ERROR:root:    handler.recv()
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 187, in recv
ERROR:root:    self.process_message()
ERROR:root:  File "/Users/*****/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 94, in process_message
ERROR:root:    data = json.loads(message.replace(b'\t', b' ' * 8).decode('utf8'))
ERROR:root:  File "./python3.3/json/__init__.py", line 316, in loads
ERROR:root:  File "./python3.3/json/decoder.py", line 351, in decode
ERROR:root:  File "./python3.3/json/decoder.py", line 367, in raw_decode
ERROR:root:ValueError: Expecting ':' delimiter: line 1 column 4099 (char 4098)
```

## Steps to Reproduce
Not sure. I just restarted sublime and downloaded the latest version of
anaconda

## ST3, Anaconda and OS versions
3208
10.14.5
2.1.33

## Anaconda's JsonServer Logs
No logs generated for this timeframe.
==

**Comment by adudek16** [comment]
Haven't seen this repeated
