### ISSUE TITLE
Cannot install anndata2ri

### ISSUE THREAD

**Issue by grimwoo** [DamnWidget/anaconda#833]
### I tried 3 ways to install anndata2ri though Python 3.6.8 Anaconda, Inc. in my server, but none of them worked. The methods I tried are: conda install, pip install git+https..., and local pip install. The code and error are listed bellow. Thank you so much.

**_(base) [wuhaoda@ln01 ~]$ source activate Grim3.6.8_**

**_(Grim3.6.8) [wuhaoda@ln01 ~]$ pip install --upgrade pip_**
Collecting pip
  Downloading https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl (1.4MB)
     |████████████████████████████████| 1.4MB 196kB/s
Installing collected packages: pip
  Found existing installation: pip 19.2.1
    Uninstalling pip-19.2.1:
      Successfully uninstalled pip-19.2.1
Successfully installed pip-19.2.3

_**(Grim3.6.8) [wuhaoda@ln01 ~]$ pip install git+https://github.com/flying-sheep/anndata2ri.git**_
Collecting git+https://github.com/flying-sheep/anndata2ri.git
  Cloning https://github.com/flying-sheep/anndata2ri.git to /tmp/pip-req-build-mgkdhoq1
  Running command git clone -q https://github.com/flying-sheep/anndata2ri.git /tmp/pip-req-build-mgkdhoq1
  fatal: Unable to find remote helper for 'https'
ERROR: Command errored out with exit status 128: git clone -q https://github.com/flying-sheep/anndata2ri.git /tmp/pip-req-build-mgkdhoq1 Check the logs for full command output.

**_(Grim3.6.8) [wuhaoda@ln01 ~]$ pip install git+git://github.com/flying-sheep/anndata2ri.git_**
Collecting git+git://github.com/flying-sheep/anndata2ri.git
  Cloning git://github.com/flying-sheep/anndata2ri.git to /tmp/pip-req-build-gr6919d1
  Running command git clone -q git://github.com/flying-sheep/anndata2ri.git /tmp/pip-req-build-gr6919d1
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/bin/python /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metad
ata_for_build_wheel /tmp/tmpssqxmig3
         cwd: /tmp/pip-req-build-gr6919d1
    Complete output (35 lines):
    The file description seems not to be valid rst for PyPI; it will be interpreted as plain text
    <string>:24: (WARNING/2) Cannot analyze code. Pygments package not found.
    
    Traceback (most recent call last):
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-zxvj6k82/overlay/lib/python3.6/site-packages/flit/buildapi.py", line 27, in prepare_metadata_for_build_wheel
        metadata = make_metadata(module, ini_info)
      File "/tmp/pip-build-env-zxvj6k82/overlay/lib/python3.6/site-packages/flit/common.py", line 302, in make_metadata
        md_dict.update(get_info_from_module(module))
      File "/tmp/pip-build-env-zxvj6k82/overlay/lib/python3.6/site-packages/flit/common.py", line 113, in get_info_from_module
        docstring, version = get_docstring_and_version_via_import(target)
      File "/tmp/pip-build-env-zxvj6k82/overlay/lib/python3.6/site-packages/flit/common.py", line 97, in get_docstring_and_version_via_import
        m = sl.load_module()
      File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 823, in load_module
      File "<frozen importlib._bootstrap_external>", line 682, in load_module
      File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 684, in _load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-req-build-gr6919d1/anndata2ri/__init__.py", line 10, in <module>
        from rpy2.rinterface import Sexp
      File "/tmp/pip-build-env-zxvj6k82/normal/lib/python3.6/site-packages/rpy2/rinterface.py", line 6, in <module>
        from rpy2.rinterface_lib import openrlib
      File "/tmp/pip-build-env-zxvj6k82/normal/lib/python3.6/site-packages/rpy2/rinterface_lib/openrlib.py", line 23, in <module>
        rlib = _dlopen_rlib(R_HOME)
      File "/tmp/pip-build-env-zxvj6k82/normal/lib/python3.6/site-packages/rpy2/rinterface_lib/openrlib.py", line 19, in _dlopen_rlib
        rlib = ffi.dlopen(lib_path)
    OSError: cannot load library '/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/R/lib/libR.so': libbz2.so.1.0: cannot open shared object file: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/bin/python /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pe
p517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpssqxmig3 Check the logs for full command output.

**_(Grim3.6.8) [wuhaoda@ln01 ~]$ cd /public-supool/home/wuhaoda/Scanpy/Download/anndata2ri-master_**

_**(Grim3.6.8) [wuhaoda@ln01 anndata2ri-master]$ pip install .**_
Processing /public-supool/home/wuhaoda/Scanpy/Download/anndata2ri-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/bin/python /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metad
ata_for_build_wheel /tmp/tmpdm6sf8p5
         cwd: /tmp/pip-req-build-ogh4noyy
    Complete output (35 lines):
    The file description seems not to be valid rst for PyPI; it will be interpreted as plain text
    <string>:24: (WARNING/2) Cannot analyze code. Pygments package not found.
    
    Traceback (most recent call last):
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-mhdg711m/overlay/lib/python3.6/site-packages/flit/buildapi.py", line 27, in prepare_metadata_for_build_wheel
        metadata = make_metadata(module, ini_info)
      File "/tmp/pip-build-env-mhdg711m/overlay/lib/python3.6/site-packages/flit/common.py", line 302, in make_metadata
        md_dict.update(get_info_from_module(module))
      File "/tmp/pip-build-env-mhdg711m/overlay/lib/python3.6/site-packages/flit/common.py", line 113, in get_info_from_module
        docstring, version = get_docstring_and_version_via_import(target)
      File "/tmp/pip-build-env-mhdg711m/overlay/lib/python3.6/site-packages/flit/common.py", line 97, in get_docstring_and_version_via_import
        m = sl.load_module()
      File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 823, in load_module
      File "<frozen importlib._bootstrap_external>", line 682, in load_module
      File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 684, in _load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-req-build-ogh4noyy/anndata2ri/__init__.py", line 10, in <module>
        from rpy2.rinterface import Sexp
      File "/tmp/pip-build-env-mhdg711m/normal/lib/python3.6/site-packages/rpy2/rinterface.py", line 6, in <module>
        from rpy2.rinterface_lib import openrlib
      File "/tmp/pip-build-env-mhdg711m/normal/lib/python3.6/site-packages/rpy2/rinterface_lib/openrlib.py", line 23, in <module>
        rlib = _dlopen_rlib(R_HOME)
      File "/tmp/pip-build-env-mhdg711m/normal/lib/python3.6/site-packages/rpy2/rinterface_lib/openrlib.py", line 19, in _dlopen_rlib
        rlib = ffi.dlopen(lib_path)
    OSError: cannot load library '/public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/R/lib/libR.so': libbz2.so.1.0: cannot open shared object file: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/bin/python /public-supool/home/wuhaoda/anaconda2/envs/Grim3.6.8/lib/python3.6/site-packages/pip/_vendor/pe
p517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpdm6sf8p5 Check the logs for full command output.

**_(Grim3.6.8) [wuhaoda@ln01 anndata2ri-master]$ flit install_**
bash: flit: command not found...

I have started an issue in anndata2ri, and got the reply as follow:
###################################
You seem to have a wonky git installation: https://stackoverflow.com/a/13018777

File "…/rpy2/rinterface_lib/openrlib.py", line 19, in _dlopen_rlib
    rlib = ffi.dlopen(lib_path)
OSError: cannot load library '…/lib/R/lib/libR.so': libbz2.so.1.0: cannot open shared object file: No such file or directory
Also a problem with you installation: Either you’re missing libbz2 or libR links to the wrong one or something.

You should file an issue with anaconda for this.

flit: command not found...

Well, you need to pip install flit for this, but it’ll also yield the earlier error.
###################################

**Comment by DamnWidget** [comment]
Wrong project, you are probably looking for: https://github.com/ContinuumIO/anaconda-issues
