### ISSUE TITLE
Anaconda jsonserver is not starting

### ISSUE THREAD

**Issue by sartoriius** [DamnWidget/anaconda#865]
## Expected Behaviour
Anaconda linting and autocompletion works and jsonserver.py starts with Sublime Text 3.2.2 build 3211.

## Actual Behaviour
jsonserver.py does not start at all (`ps aux | grep jsonserver` returns no running servers even though ST3 is running).
Autocompletion and linting do not work.
Every time I left click, backspace, or type into a .py file I also receive console errors.

## Steps to Reproduce
Unsure of the steps required to have this error...

## ST3, Anaconda and OS versions
ST3: v3.2.2 build 3211
Anaconda: v2.1.36
OS: macOS Catalina 10.15.5

## ST3 Console Logs
**Logs upon starting ST3:**
```
startup, version: 3211 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/sso/Library/Application Support/Sublime Text 3/Packages
state path: /Users/sso/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/sso/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.525038
using gpu buffer for window
startup time: 0.693906
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-sublime_lib
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pathlib
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.plugin
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin gruvbox.main
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageDev._logging
reloading plugin PackageDev.main
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 606, in plugin_loaded
    ColorHighlighterPlugin.init()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 319, in init
    ColorHighlighterPlugin._fake_color_scheme = ColorHighlighterPlugin.components.provide_fake_color_scheme()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 197, in provide_fake_color_scheme
    return self.provide_fake_color_scheme_data()[0]
  File "/Users/sso/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 188, in provide_fake_color_scheme_data
    self._fake_color_scheme_data = parse_color_scheme(self.provide_color_scheme(), self._settings.debug)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/color_scheme.py", line 43, in parse_color_scheme
    color_scheme_xml = ElementTree.fromstring(color_scheme_content)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 619, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 124, in on_activated
    self.run_linter(view)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 75, in _start_worker
    wk.start()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 52, in start
    self._update_python_builder()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 98, in _update_python_builder
    self.interpreter.python
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
Traceback (most recent call last):
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 47, in lint
    self.run_linter(view)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 75, in _start_worker
    wk.start()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 52, in start
    self._update_python_builder()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 98, in _update_python_builder
    self.interpreter.python
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
Package Control: Skipping automatic upgrade, last run at 2020-07-03 00:41:19, next run at 2020-07-03 01:41:19 or after
```

**Left click gives:** 
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 619, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 124, in on_activated
    self.run_linter(view)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 75, in _start_worker
    wk.start()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 52, in start
    self._update_python_builder()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 98, in _update_python_builder
    self.interpreter.python
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
```

**Typing gives:**
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 619, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 124, in on_activated
    self.run_linter(view)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 380, in run_linter
    Worker().execute(Callback(on_success=parse_results), **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 75, in _start_worker
    wk.start()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 52, in start
    self._update_python_builder()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 98, in _update_python_builder
    self.interpreter.python
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
ERROR:root:Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 688, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/decorators.py", line 142, in wrapper
    result = func(*args, **kwargs)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/completion.py", line 61, in on_query_completions
    Worker().execute(self._complete, **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 108, in execute
    _start_worker(worker, callback, **data)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 75, in _start_worker
    wk.start()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 52, in start
    self._update_python_builder()
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/local_worker.py", line 98, in _update_python_builder
    self.interpreter.python
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 42, in update_interpreter_build_system
    current_list[i] = self._parse_tpl(cmd)
  File "/Users/sso/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/builder/python_builder.py", line 78, in _parse_tpl
    template.safe_substitute({'python_interpreter': cmd})
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
```

**Backspacing gives:** 
```
ERROR:root:Error trying to decode value: Unexpected character, expected a comma or closing bracket in (data):3:22
```

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

There is only a folder called "test" with the log file inside. This folder appeared after running the command: `python -B anaconda_server/jsonserver.py -p test 9999 DEBUG` in the terminal. My Python is run from within a conda environment and `where python` returns `/Users/sso/opt/miniconda3/envs/ROC/bin/python` and `/usr/bin/python`. After running the command I got the output:
```
MyPy is enabled but we could not import it
DEBUG:root:bind: address=('localhost', 9999)
DEBUG:root:listen: backlog=5
INFO:root:Anaconda Server started in 9999 for PID DEBUG with cache dir /Users/sso/Library/Caches/Jedi/test
INFO:root:Anaconda Server started in DEBUG mode...
DEBUG MODE
```

Unsure why it is calling MyPy because I haven't set MyPy to true and the default in Anaconda is false.

The contents of the logfile are as below:
```
2020-07-03 00:23:55,553: DEBUG   : bind: address=('localhost', 9999)
2020-07-03 00:23:55,554: DEBUG   : listen: backlog=5
2020-07-03 00:23:55,555: INFO    : Anaconda Server started in 9999 for PID DEBUG with cache dir /Users/sso/Library/Caches/Jedi/test
2020-07-03 00:23:55,555: INFO    : Anaconda Server started in DEBUG mode...
2020-07-03 01:07:25,493: DEBUG   : bind: address=('localhost', 9999)
2020-07-03 01:07:25,494: DEBUG   : listen: backlog=5
2020-07-03 01:07:25,494: INFO    : Anaconda Server started in 9999 for PID DEBUG with cache dir /Users/sso/Library/Caches/Jedi/test
2020-07-03 01:07:25,494: INFO    : Anaconda Server started in DEBUG mode...
```

The files and folder owners are all my user.

## Extra information
I am using a project file, which has the following settings (interpreter set to use the Python installed in the conda environment called ROC):
```
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"/Users/sso/opt/miniconda3/envs/ROC/bin/python3\" -u \"$file\""
		}
	],
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	{
		"python_interpreter": "\"/Users/sso/opt/miniconda3/envs/ROC/bin/python3\""
	}
}
```

**My user settings:**
```
{
    "python_interpreter": "\"/Users/sso/opt/miniconda3/bin/python3\""
}
```

Building Python files seems to work. Within the project, if I try to build a test file with the following contents:
```
import sys
print(sys.version_info)
```
I get the output `sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)`. I can also import modules that are installed only in the ROC environment, which are not installed in other environments.

I am a bit new to using Sublime and also am still learning about Python so I hope you guys can help me resolve these issues.
Essentially, I am unsure what is wrong with my configuration that does not allow jsonserver to start to enable autocompletion and linting.

**Comment by sartoriius** [comment]
Fixed by setting `"python_interpreter": "/Users/sso/opt/miniconda3/bin/python3"` - removed extra \" quotes surrounding the interpreter.

Strongly apologise for opening an issue over something so trivial!! It was an error brought over from when I was copying the style of my Windows settings.
