### ISSUE TITLE
Remote interpreter in docker instance : "Unfortunately, the Windows socket is in inconsistent state, restart your sublime text 3"

### ISSUE THREAD

**Issue by nicolas-renard** [DamnWidget/anaconda#872]
## Expected Behaviour
Hello,

I'm trying to connect my sublime text to a remote interpreter running in a local docker using Docker Desktop.

The remote interpreter should work properly from docker image

## Actual Behaviour
I get no linting and not autocompletion. After a few seconds, I get an error message in a new ST window : "Unfortunately, the Windows socket is in inconsistent state, restart your sublime text 3".
Restarting ST3 always produce the same result.

## Steps to Reproduce
1- Docker command to run (using powershell in my case) : ```docker run --rm -it -v "C:\[local_path]\AppData\Roaming\Sublime Text 3\Packages\Anaconda:/opt/anaconda" -p 9999:9999 python:3.6-slim-stretch /opt/anaconda/anaconda_server/docker/start python 9999 docker_project```
(I usually add a -d option, removed it to see the logs at the same time)

2- Open a sublime text project with the following .sublime-project file :
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"python_interpreter": "tcp://localhost:9999"
	}
}
```

3- Go to a .py file and try writing something (ex : import ...)

Notes : 
- This setup works on my personnal computer
- It doesn't work on my work computer
- My work computer is behind a corporate proxy (but I also tried it without the proxy using my phone as modem : same error)
- Seeing the logs, it seems the distant anaconda minserver (running on the docker host) receive the connexions from ST3. But it shows an error at some point and I couldn't figure it out when I tried to dive into anaconda code (not familiar at all with the code base)

## ST3, Anaconda and OS versions

- ST3 3.2.2, build 3211
- Anaconda v2.1.37
- OS : Windows 10 v1909

## ST3 Console Logs
After the plugin's reloading : 
```
plugins loaded
[PackageDev.plugins_.settings] ERROR: Not a Sublime Text Settings or Project file: None
[2020-10-05 15:56:18,881 - ERROR    - PackageDev.plugins_.settings] Not a Sublime Text Settings or Project file: None
[2020-10-05 15:56:19,232 - ERROR    - root] Unfortunately, the Windows socket is in inconsistent state, restart your sublime text 3. If the problem persist, fill an issue report on:   https://github.com/DamnWidget/anaconda/issues
error: Unfortunately, the Windows socket is in inconsistent state, restart your sublime text 3. If the problem persist, fill an issue report on:   https://github.com/DamnWidget/anaconda/issues
Package Control: Skipping automatic upgrade, last run at 2020-10-05 15:22:06, next run at 2020-10-05 16:22:06 or after
```

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

```
MyPy is enabled but we could not import it
DEBUG:root:bind: address=('0.0.0.0', 9999)
DEBUG:root:listen: backlog=5
INFO:root:Anaconda Server started in port 9999 with cache dir /root/.cache/jedi/docker_project and extra paths /
2020-10-05 13:56:11,393: DEBUG   : bind: address=('0.0.0.0', 9999)
2020-10-05 13:56:11,393: DEBUG   : listen: backlog=5
2020-10-05 13:56:11,394: INFO    : Anaconda Server started in port 9999 with cache dir /root/.cache/jedi/docker_project and extra paths /
INFO:root:Incomming connection from ('172.17.0.1', 44818)
INFO:root:Incomming connection from ('172.17.0.1', 44822)
INFO:root:client requests: lint
error: uncaptured python exception, closing channel <__main__.JSONHandler connected 172.17.0.1:44822 at 0x7f3b6e471a90> (<class 'AttributeError'>:'function' object has no attribute 'get' [/usr/local/lib/python3.6/asyncore.py|read|83] [/usr/local/lib/python3.6/asyncore.py|handle_read_event|423] [/usr/local/lib/python3.6/asynchat.py|handle_read|171] [/opt/anaconda/anaconda_server/minserver.py|found_terminator|94] [/opt/anaconda/anaconda_server/minserver.py|handle_command|112] [/opt/anaconda/anaconda_server/lib/anaconda_handler.py|run|49] [/opt/anaconda/anaconda_server/handlers/python_lint_handler.py|lint|49] [/opt/anaconda/anaconda_server/handlers/python_lint_handler.py|_configure_linters|163])
2020-10-05 13:56:18,893: INFO    : Incomming connection from ('172.17.0.1', 44818)
2020-10-05 13:56:18,894: INFO    : Incomming connection from ('172.17.0.1', 44822)
2020-10-05 13:56:18,904: INFO    : client requests: lint
INFO:root:Incomming connection from ('172.17.0.1', 44826)
INFO:root:Incomming connection from ('172.17.0.1', 44830)
INFO:root:client requests: autocomplete
error: uncaptured python exception, closing channel <__main__.JSONHandler connected 172.17.0.1:44830 at 0x7f3b6e8c5fd0> (<class 'AttributeError'>:'function' object has no attribute 'get' [/usr/local/lib/python3.6/asyncore.py|read|83] [/usr/local/lib/python3.6/asyncore.py|handle_read_event|423] [/usr/local/lib/python3.6/asynchat.py|handle_read|171] [/opt/anaconda/anaconda_server/minserver.py|found_terminator|94] [/opt/anaconda/anaconda_server/minserver.py|handle_command|112] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|run|29] [/opt/anaconda/anaconda_server/lib/anaconda_handler.py|run|49] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|autocomplete|71] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|script|45] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|jedi_script|52])
INFO:root:Incomming connection from ('172.17.0.1', 44834)
INFO:root:Incomming connection from ('172.17.0.1', 44838)
2020-10-05 13:56:19,211: INFO    : Incomming connection from ('172.17.0.1', 44826)
2020-10-05 13:56:19,212: INFO    : Incomming connection from ('172.17.0.1', 44830)
2020-10-05 13:56:19,223: INFO    : client requests: autocomplete
2020-10-05 13:56:19,767: INFO    : Incomming connection from ('172.17.0.1', 44834)
2020-10-05 13:56:19,771: INFO    : Incomming connection from ('172.17.0.1', 44838)
```

**Comment by nicolas-renard** [comment]
Hello,

Diving more into the issue, I came up with something : 

- The working version on my personal computer was with Anaconda v2.1.36

I manually installed anaconda 2.1.36 on my work computer and it worked perfectly. I edited my previous post accordingly.

So the 2.1.37 inserted a regression using remote interpreter.
Again, I'm not super familiar with anaconda's base code, so appologies in advance for innacuracies, but printing elements with v2.1.36 and with 2.1.37, for the linting command, the issue seems to be that in the `anaconda_server > handlers > python_lint_handler.py` file, in the `_configure_linters` method, in the 2.1.36 version, the passed `settings` parameter is a json object (so having a `get` method), but in the 2.1.37, the method has no parameter and use its internal object `self.settings`, but this object is not a JSON object, but a `JSONHandler.return_back` method (defined in `minserver.py`).
I guess the self.settings object was not modified somewhere along the road, not sure where exactly. In the AnacondaHandler().run methd definition maybe ? On the definition of the command kwargs ? (don't know if any other method in the PythonLintHandler requires the use of the JSONHandler.return_back method and so if it can be replaced)

**Comment by DamnWidget** [comment]
Thanks for looking into this, unfortunately I have no time to dedicate to hunting this kind of things in anaconda anymore, has been 6 years already that I do not work with Python or Sublime Text 3 at all, so my personal investment is close to zero at this point, looks like you might be on the right path, honestly, I do not even remember how the docker support for remote interpreter was implemented at this point.

You could coordinate efforts with @scuml as he is the author of majority of changes in Anaconda nowadays

**Comment by nicolas-renard** [comment]
Thanks for your answer !

@scuml : any comments / ideas regarding this issue ?

**Comment by relikd** [comment]
@nicolas-renard It is a shot in the dark, but can you try this please:

replace line 53 in `Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py`
```python
jedi_project._environment_path = self.settings.get("python_interpreter")
```
with:
```python
os.environ.setdefault('VIRTUAL_ENV', self.settings.get("python_interpreter"))
```
(you will need to `import os` at the top)

**Comment by nicolas-renard** [comment]
@relikd : thanks for your reply

Tested it with 2.1.37 : not working, still the same errors

**Comment by nicolas-renard** [comment]
update @scuml 

Tested it with the most recent released version (2.2.0), still not working. I don't always have the error message "Windows socket in inconsistent state", but the anaconda remote interpreter is not working with sometimes different errors though (same error for the lint operation, different for the autoComplete one) :

## ST3, Anaconda and OS versions

- ST3 3.2.2, build 3211
- **Anaconda v2.2.0**
- OS : Windows 10 v1909

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

````
MyPy is enabled but we could not import it
DEBUG:root:bind: address=('0.0.0.0', 9999)
DEBUG:root:listen: backlog=5
INFO:root:Anaconda Server started in port 9999 with cache dir /root/.cache/jedi/docker_project and extra paths /sandbox
2020-10-22 09:31:47,280: DEBUG   : bind: address=('0.0.0.0', 9999)
2020-10-22 09:31:47,280: DEBUG   : listen: backlog=5
2020-10-22 09:31:47,280: INFO    : Anaconda Server started in port 9999 with cache dir /root/.cache/jedi/docker_project and extra paths /sandbox
INFO:root:Incomming connection from ('172.17.0.1', 38138)
INFO:root:Incomming connection from ('172.17.0.1', 38142)
INFO:root:client requests: lint
error: uncaptured python exception, closing channel <__main__.JSONHandler connected 172.17.0.1:38142 at 0x7fa54bbd4cc0> (<class 'AttributeError'>:'function' object has no attribute 'get' [/usr/local/lib/python3.6/asyncore.py|read|83] [/usr/local/lib/python3.6/asyncore.py|handle_read_event|423] [/usr/local/lib/python3.6/asynchat.py|handle_read|171] [/opt/anaconda/anaconda_server/minserver.py|found_terminator|94] [/opt/anaconda/anaconda_server/minserver.py|handle_command|112] [/opt/anaconda/anaconda_server/lib/anaconda_handler.py|run|49] [/opt/anaconda/anaconda_server/handlers/python_lint_handler.py|lint|49] [/opt/anaconda/anaconda_server/handlers/python_lint_handler.py|_configure_linters|163])
INFO:root:Incomming connection from ('172.17.0.1', 38146)
INFO:root:Incomming connection from ('172.17.0.1', 38150)
INFO:root:client requests: lint
error: uncaptured python exception, closing channel <__main__.JSONHandler connected 172.17.0.1:38150 at 0x7fa54bbd4cc0> (<class 'AttributeError'>:'function' object has no attribute 'get' [/usr/local/lib/python3.6/asyncore.py|read|83] [/usr/local/lib/python3.6/asyncore.py|handle_read_event|423] [/usr/local/lib/python3.6/asynchat.py|handle_read|171] [/opt/anaconda/anaconda_server/minserver.py|found_terminator|94] [/opt/anaconda/anaconda_server/minserver.py|handle_command|112] [/opt/anaconda/anaconda_server/lib/anaconda_handler.py|run|49] [/opt/anaconda/anaconda_server/handlers/python_lint_handler.py|lint|49] [/opt/anaconda/anaconda_server/handlers/python_lint_handler.py|_configure_linters|163])
2020-10-22 09:31:54,350: INFO    : Incomming connection from ('172.17.0.1', 38138)
2020-10-22 09:31:54,352: INFO    : Incomming connection from ('172.17.0.1', 38142)
2020-10-22 09:31:54,361: INFO    : client requests: lint
2020-10-22 09:31:54,412: INFO    : Incomming connection from ('172.17.0.1', 38146)
2020-10-22 09:31:54,416: INFO    : Incomming connection from ('172.17.0.1', 38150)
2020-10-22 09:31:54,427: INFO    : client requests: lint
INFO:root:Incomming connection from ('172.17.0.1', 38154)
INFO:root:Incomming connection from ('172.17.0.1', 38158)
INFO:root:client requests: doc
2020-10-22 09:31:56,562: INFO    : Incomming connection from ('172.17.0.1', 38154)
2020-10-22 09:31:56,563: INFO    : Incomming connection from ('172.17.0.1', 38158)
2020-10-22 09:31:56,573: INFO    : client requests: doc
error: uncaptured python exception, closing channel <__main__.JSONHandler connected 172.17.0.1:38158 at 0x7fa54bbd4dd8> (<class 'TypeError'>:'bool' object is not callable [/usr/local/lib/python3.6/asyncore.py|read|83] [/usr/local/lib/python3.6/asyncore.py|handle_read_event|423] [/usr/local/lib/python3.6/asynchat.py|handle_read|171] [/opt/anaconda/anaconda_server/minserver.py|found_terminator|94] [/opt/anaconda/anaconda_server/minserver.py|handle_command|112] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|run|29] [/opt/anaconda/anaconda_server/lib/anaconda_handler.py|run|49] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|doc|99] [/opt/anaconda/anaconda_server/commands/doc.py|__init__|33] [/opt/anaconda/anaconda_server/commands/base.py|__init__|14] [/opt/anaconda/anaconda_server/commands/doc.py|run|65] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|handle_result_and_purge_cache|39])
INFO:root:Incomming connection from ('172.17.0.1', 38162)
INFO:root:Incomming connection from ('172.17.0.1', 38166)
INFO:root:client requests: doc
error: uncaptured python exception, closing channel <__main__.JSONHandler connected 172.17.0.1:38166 at 0x7fa54b9e4470> (<class 'TypeError'>:'bool' object is not callable [/usr/local/lib/python3.6/asyncore.py|read|83] [/usr/local/lib/python3.6/asyncore.py|handle_read_event|423] [/usr/local/lib/python3.6/asynchat.py|handle_read|171] [/opt/anaconda/anaconda_server/minserver.py|found_terminator|94] [/opt/anaconda/anaconda_server/minserver.py|handle_command|112] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|run|29] [/opt/anaconda/anaconda_server/lib/anaconda_handler.py|run|49] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|doc|99] [/opt/anaconda/anaconda_server/commands/doc.py|__init__|33] [/opt/anaconda/anaconda_server/commands/base.py|__init__|14] [/opt/anaconda/anaconda_server/commands/doc.py|run|65] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|handle_result_and_purge_cache|39])
2020-10-22 09:31:57,913: INFO    : Incomming connection from ('172.17.0.1', 38162)
2020-10-22 09:31:57,915: INFO    : Incomming connection from ('172.17.0.1', 38166)
2020-10-22 09:31:57,922: INFO    : client requests: doc
INFO:root:Incomming connection from ('172.17.0.1', 38170)
INFO:root:Incomming connection from ('172.17.0.1', 38174)
INFO:root:client requests: lint
error: uncaptured python exception, closing channel <__main__.JSONHandler connected 172.17.0.1:38174 at 0x7fa54ad5a9b0> (<class 'AttributeError'>:'function' object has no attribute 'get' [/usr/local/lib/python3.6/asyncore.py|read|83] [/usr/local/lib/python3.6/asyncore.py|handle_read_event|423] [/usr/local/lib/python3.6/asynchat.py|handle_read|171] [/opt/anaconda/anaconda_server/minserver.py|found_terminator|94] [/opt/anaconda/anaconda_server/minserver.py|handle_command|112] [/opt/anaconda/anaconda_server/lib/anaconda_handler.py|run|49] [/opt/anaconda/anaconda_server/handlers/python_lint_handler.py|lint|49] [/opt/anaconda/anaconda_server/handlers/python_lint_handler.py|_configure_linters|163])
INFO:root:Incomming connection from ('172.17.0.1', 38178)
INFO:root:Incomming connection from ('172.17.0.1', 38182)
INFO:root:client requests: autocomplete
DEBUG:parso.python.diff:diff parser start
DEBUG:parso.python.diff:line_lengths old: 5; new: 5
DEBUG:parso.python.diff:-> code[replace] old[1:1] new[1:1]
DEBUG:parso.python.diff:parse_part from 1 to 1 (to 2 in part parser)
DEBUG:parso.python.diff:-> code[equal] old[2:5] new[2:5]
DEBUG:parso.python.diff:copy old[3:4] new[2:5]
DEBUG:parso.python.diff:diff parser end
ERROR:root:The underlying Jedi library as raised an exception
ERROR:root:'bool' object is not callable
Traceback (most recent call last):
  File "/opt/anaconda/anaconda_server/commands/autocomplete.py", line 34, in run
    'success': True, 'completions': data, 'uid': self.uid
  File "/opt/anaconda/anaconda_server/handlers/jedi_handler.py", line 39, in handle_result_and_purge_cache
    self.real_callback(result)
TypeError: 'bool' object is not callable

error: uncaptured python exception, closing channel <__main__.JSONHandler connected 172.17.0.1:38182 at 0x7fa54addec18> (<class 'TypeError'>:'bool' object is not callable [/usr/local/lib/python3.6/asyncore.py|read|83] [/usr/local/lib/python3.6/asyncore.py|handle_read_event|423] [/usr/local/lib/python3.6/asynchat.py|handle_read|171] [/opt/anaconda/anaconda_server/minserver.py|found_terminator|94] [/opt/anaconda/anaconda_server/minserver.py|handle_command|112] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|run|29] [/opt/anaconda/anaconda_server/lib/anaconda_handler.py|run|49] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|autocomplete|69] [/opt/anaconda/anaconda_server/commands/autocomplete.py|__init__|19] [/opt/anaconda/anaconda_server/commands/base.py|__init__|14] [/opt/anaconda/anaconda_server/commands/autocomplete.py|run|45] [/opt/anaconda/anaconda_server/handlers/jedi_handler.py|handle_result_and_purge_cache|39])
2020-10-22 09:31:58,080: INFO    : Incomming connection from ('172.17.0.1', 38170)
2020-10-22 09:31:58,082: INFO    : Incomming connection from ('172.17.0.1', 38174)
2020-10-22 09:31:58,086: INFO    : client requests: lint
2020-10-22 09:31:58,340: INFO    : Incomming connection from ('172.17.0.1', 38178)
2020-10-22 09:31:58,342: INFO    : Incomming connection from ('172.17.0.1', 38182)
2020-10-22 09:31:58,357: INFO    : client requests: autocomplete
2020-10-22 09:31:58,359: DEBUG   : diff parser start
2020-10-22 09:31:58,360: DEBUG   : line_lengths old: 5; new: 5
2020-10-22 09:31:58,361: DEBUG   : -> code[replace] old[1:1] new[1:1]
2020-10-22 09:31:58,364: DEBUG   : parse_part from 1 to 1 (to 2 in part parser)
2020-10-22 09:31:58,365: DEBUG   : -> code[equal] old[2:5] new[2:5]
2020-10-22 09:31:58,367: DEBUG   : copy old[3:4] new[2:5]
2020-10-22 09:31:58,368: DEBUG   : diff parser end
2020-10-22 09:31:58,641: ERROR   : The underlying Jedi library as raised an exception
2020-10-22 09:31:58,642: ERROR   : 'bool' object is not callable
````

**Comment by llan-ml** [comment]
Hi @scuml , I tested the function of remote interpreter with v2.2.0 and it did not work normally. In particular, I used Sublime on Windows and tried starting a remote interpreter in a Ubuntu server. 

The remote `JsonServer` shows the same log information as @nicolas-renard reported above. 

Can you take a look into this issue if you have time? I really like the remote interpreter function but the jedi used by v2.1.36 is quite old. Thank you!
