### ISSUE TITLE
Anaconda stop working after 2nd restart following installation

### ISSUE THREAD

**Issue by tronghieu1987** [DamnWidget/anaconda#875]
I have noticed that probably since the latest version, Anaconda in Sublime only works after the first restart after installation. From the 2nd time Sublime is restarted, Go To commands will show "Unable to find package  xyz" in Sublime  status bar.

One trick to get it back to work is to put "Anaconda" to the Ignored Package list, save the settings, restart Sublime, then remove it from Ignored list, save the settings, then boom it's back to work. But then any subsequent restart will make Anaconda stop working again. I am not sure if the issue has anything to do with the order that packages are loaded, but this trick makes Anaconda, the setup and version files be reloaded again in the end of the log, just like how they are in the 1st restart after the installation. In contrast, in the subsequent restarts that make Anaconda to fail, the files are loaded in the middle of the log.

## Steps to Reproduce
- Install a fresh Anaconda package
- Restart Sublime. Then Anaconda would work
- Restart Sublime again, Anaconda would stop working and display "Unable to find package xyz"

## ST3, Anaconda and OS versions
ST3 3.1.1; Windows 10, Anaconda latest version

## ST3 Console Logs When working
DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/C0WN2/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/C0WN2/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/C0WN2/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "Anaconda"]
pre session restore time: 0.367573
startup time: 0.511573
first paint time: 0.515573
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.10-wcwidth
reloading plugin 0_package_control_loader.40-pywinpty
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-puresasl
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin All Autocomplete.all_views_completions
reloading plugin AutoDocstring.auto_docstring
reloading plugin AutoDocstring.autodocstring_logging
reloading plugin AutoDocstring.docstring_styles
reloading plugin AutoDocstring.dparse
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin FileDiffs.file_diffs
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin Indent XML.indentxml
reloading plugin Indent XML.setup
reloading plugin IndentToAllBrackets.better_auto_indent
reloading plugin LineJumper.line_jumper
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin SAS Syntax and Theme.run_sas_program
reloading plugin SAS Syntax and Theme.show_next_error
reloading plugin SelectUntil.edit
reloading plugin SelectUntil.select-until
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SqlBeautifier.sqlbeautifier
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter._init
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.quick_actions
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin xml2json.ordereddict
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\C0WN2\AppData\Roaming\Sublime Text 3\Installed Packages\xml2json.sublime-package\ordereddict.py", line 23, in <module>
ImportError: No module named 'UserDict'
reloading plugin xml2json.Xml2json
reloading plugin xml2json.xmltodict
reloading plugin better_auto_indent
reloading plugin SAS.sasAutoComplete
reloading plugin SFTP.SFTP
reloading plugin SQLTools.SQLTools
Finish downloading Data Lake meta JSON files in  3.7642481327056885
reloading plugin SublimeEyeball.eyeball_select
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin User.better_auto_indent
reloading plugin User.pathway
PATH = C:\Oracle12c\product\12.1.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\SASHome\x86\Secure\ccme4;C:\Program Files\SASHome\Secure\ccme4;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;c:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\System32\OpenSSH\;C:\Oracle12c\product\12.1.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\SASHome\x86\Secure\ccme4;C:\Program Files\SASHome\Secure\ccme4;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Users\C0WN2\AppData\Local\Microsoft\WindowsApps;C:\Progra~2\Java\jre1.8.0_141\bin;C:\Progra~2\Java\jre1.8.0_141;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\bin;C:\ProgramData\Anaconda3\condabin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Scripts;C:\Users\C0WN2\Documents\Python\Hadoop;C:\Users\C0WN2\Documents\Python\Hadoop\bin;C:\Users\C0WN2\Documents\SAS;C:\Users\C0WN2\Documents\SAS\deploywiz__94230__prt__xx__sp0__1;C:\Users\C0WN2\Documents\SAS\deploywiz__94230__prt__xx__sp0__1\deploywiz;C:\ProgramData\Anaconda3\python.exe;C:\Program Files\Git\usr\bin\ssh.exe;C:\Program Files\Git\usr\bin;C:\ClouderaCLI;;C:\Users\C0WN2\AppData\Local\Microsoft\WindowsApps:/usr/local/bin:/usr/local/sbin:/Users/Rob/.rvm/bin:
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2020-10-08 11:40:12, next run at 2020-10-08 12:40:12 or after
Unable to open /C/Users/C0WN2/AppData/Roaming/Sublime Text 3/Packages/Default/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
generating meta info summary

## ST3 Console Logs When NOT working
DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/C0WN2/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/C0WN2/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/C0WN2/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.699188
startup time: 0.934188
first paint time: 0.940188
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.10-wcwidth
reloading plugin 0_package_control_loader.40-pywinpty
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-puresasl
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin All Autocomplete.all_views_completions
reloading plugin AutoDocstring.auto_docstring
reloading plugin AutoDocstring.autodocstring_logging
reloading plugin AutoDocstring.docstring_styles
reloading plugin AutoDocstring.dparse
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin FileDiffs.file_diffs
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin Indent XML.indentxml
reloading plugin Indent XML.setup
reloading plugin IndentToAllBrackets.better_auto_indent
reloading plugin LineJumper.line_jumper
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
reloading plugin SAS Syntax and Theme.run_sas_program
reloading plugin SAS Syntax and Theme.show_next_error
reloading plugin SelectUntil.edit
reloading plugin SelectUntil.select-until
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SqlBeautifier.sqlbeautifier
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter._init
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.quick_actions
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin xml2json.ordereddict
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\C0WN2\AppData\Roaming\Sublime Text 3\Installed Packages\xml2json.sublime-package\ordereddict.py", line 23, in <module>
ImportError: No module named 'UserDict'
reloading plugin xml2json.Xml2json
reloading plugin xml2json.xmltodict
reloading plugin better_auto_indent
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin SAS.sasAutoComplete
reloading plugin SFTP.SFTP
reloading plugin SQLTools.SQLTools
Finish downloading Data Lake meta JSON files in  3.929919958114624
reloading plugin SublimeEyeball.eyeball_select
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin User.better_auto_indent
reloading plugin User.pathway
PATH = C:\Oracle12c\product\12.1.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\SASHome\x86\Secure\ccme4;C:\Program Files\SASHome\Secure\ccme4;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;c:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\System32\OpenSSH\;C:\Oracle12c\product\12.1.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\SASHome\x86\Secure\ccme4;C:\Program Files\SASHome\Secure\ccme4;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Users\C0WN2\AppData\Local\Microsoft\WindowsApps;C:\Progra~2\Java\jre1.8.0_141\bin;C:\Progra~2\Java\jre1.8.0_141;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\bin;C:\ProgramData\Anaconda3\condabin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Scripts;C:\Users\C0WN2\Documents\Python\Hadoop;C:\Users\C0WN2\Documents\Python\Hadoop\bin;C:\Users\C0WN2\Documents\SAS;C:\Users\C0WN2\Documents\SAS\deploywiz__94230__prt__xx__sp0__1;C:\Users\C0WN2\Documents\SAS\deploywiz__94230__prt__xx__sp0__1\deploywiz;C:\ProgramData\Anaconda3\python.exe;C:\Program Files\Git\usr\bin\ssh.exe;C:\Program Files\Git\usr\bin;C:\ClouderaCLI;;C:\Users\C0WN2\AppData\Local\Microsoft\WindowsApps:/usr/local/bin:/usr/local/sbin:/Users/Rob/.rvm/bin:
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2020-10-08 11:40:12, next run at 2020-10-08 12:40:12 or after

**Comment by relikd** [comment]
Your description of the problem ("does not work after a sublime restart") sounds a lot like #878 
Try setting the full python path in Anaconda user settings: `"python_interpreter": "/usr/bin/python"`
