### ISSUE TITLE
client requests: doc throws jedi.api.environment.InvalidPythonEnvironment

### ISSUE THREAD

**Issue by dvida** [DamnWidget/anaconda#876]
## Expected Behaviour

Requesting the function docstring should work.

## Actual Behaviour

Nothing happens on the surface, and this what the anaconda_jsonserver.log says (see below)

## Steps to Reproduce

After I got this error, I purged my prevous installation of Sublime, and installed the latest version of Sublime Text 3 (3211) and Anaconda. No change.
Also, I removed my sublime-project file and started from scratch, no change.

## ST3, Anaconda and OS versions

OS Name	Microsoft Windows 10 Home
Version	10.0.18363 Build 18363

Sublime Text 3 (3211) 
Sublime Anaconda 2.1.37

## Anaconda's JsonServer Logs

```
2020-10-04 20:35:09,025: INFO    : Anaconda Server started in 4606 for PID 3036 with cache dir C:\Users\delorayn1\AppData\Local\Jedi\Jedi\RMS and extra paths D:\Dropbox\RPi_Meteor_Station\RMS
2020-10-04 20:35:09,150: INFO    : Incoming connection from ('127.0.0.1', 4613)
2020-10-04 20:35:09,151: INFO    : Incoming connection from ('127.0.0.1', 4614)
2020-10-04 20:35:09,242: INFO    : client requests: lint
2020-10-04 21:05:10,035: INFO    : detected inactivity for more than 30 minutes... shuting down...
2020-10-04 21:05:10,036: INFO    : Closing the socket, server will be shutdown now...
2020-10-05 10:02:13,018: INFO    : client requests: lint
2020-10-05 14:58:39,679: INFO    : client requests: lint
2020-10-05 14:59:20,957: INFO    : client requests: lint
2020-10-05 14:59:21,341: INFO    : client requests: lint
2020-10-05 14:59:23,738: INFO    : client requests: lint
2020-10-05 14:59:26,841: INFO    : client requests: lint
2020-10-05 14:59:30,012: INFO    : client requests: lint
2020-10-05 14:59:31,854: INFO    : client requests: doc
2020-10-05 14:59:31,903: ERROR   : python\Scripts\python.exe seems to be missing.
2020-10-05 14:59:31,913: ERROR   : Traceback (most recent call last):
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\jsonserver.py", line 110, in found_terminator
    )
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\jsonserver.py", line 138, in handle_command
    print('{0} handler retrieved from registry'.format(handler))
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\handlers\jedi_handler.py", line 29, in run
    super(JediHandler, self).run()
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\lib\anaconda_handler.py", line 49, in run
    command(**kwargs)
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\handlers\jedi_handler.py", line 101, in doc
    Doc(self.callback, self.uid, self.script, html)
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\handlers\jedi_handler.py", line 45, in script
    return self.jedi_script(**self.data)
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\handlers\jedi_handler.py", line 56, in jedi_script
    source, int(line), int(offset), filename, encoding, project=jedi_project)
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\jedi\api\__init__.py", line 185, in __init__
    project, environment=environment, script_path=self.path
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\jedi\inference\__init__.py", line 87, in __init__
    environment = project.get_environment()
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\jedi\api\project.py", line 210, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\jedi\api\environment.py", line 377, in create_environment
    return Environment(_get_executable_path(path, safe=safe))
  File "C:\Users\delorayn1\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\jedi\api\environment.py", line 390, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: python\Scripts\python.exe seems to be missing.
```

**Comment by DamnWidget** [comment]
What is your configured python interpreter? Looks like that path is split somehow

**Comment by dvida** [comment]
Thanks for the suggestion!
I'm running Anaconda python:
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

One thing I failed to mention is that nothing was changed in the Python installation or general configuration, and the error coincided with the latest Sublime Anaconda update.

**Comment by scuml** [comment]
Please use an absolute path to the python version for the time being or leave `python_interpreter` blank to auto-detect the standard system python install.

**Comment by dvida** [comment]
I ended up purging and re-installing Anaconda Python and Sublime. Works like a charm now, thanks for all your help guys!
