### ISSUE TITLE
anaconda_lib/typing.py does not compatible with python 3.8+

### ISSUE THREAD

**Issue by zcold** [DamnWidget/anaconda#884]
## Expected Behaviour
jsonserver works
## Actual Behaviour
jsonserver does not work
## Steps to Reproduce
Set python_interpreter to python3.8.0 will let jsonserver not work.
Switch to python 3.7.4 and 3.6.0 will let jsonserver work
## ST3, Anaconda and OS versions
ST# 3.2.2 build 3211, Red Hat Enterprise Linux Server release 7.7 (Maipo)
## ST3 Console Logs
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x7f75be41dfd0> initial check failed because:

can not connect to /home/xxx/.local/share/anaconda/run/Anaconda/anaconda.sock. tried to connect 21 times during 2 seconds
## Anaconda's JsonServer Logs
jsonserver did not start
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

## python3 Anaconda/anaconda_server/jsonserver.py
Traceback (most recent call last):
  File "/home/xxx/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py", line 32, in <module>
    from handlers import ANACONDA_HANDLERS
  File "/home/xxx/workspace/sublime_sync/Packages/Anaconda/anaconda_server/handlers/__init__.py", line 11, in <module>
    from .python_lint_handler import PythonLintHandler
  File "/home/xxx/workspace/sublime_sync/Packages/Anaconda/anaconda_server/handlers/python_lint_handler.py", line 13, in <module>
    from linting.anaconda_pep8 import Pep8Linter
  File "/home/xxx/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/linting/anaconda_pep8.py", line 9, in <module>
    from linting import linter
  File "/home/xxx/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/linting/linter.py", line 30, in <module>
    import pyflakes.checker as pyflakes  # noqa
  File "/home/xxx/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/linting/pyflakes/checker.py", line 8, in <module>
    import doctest
  File "/app/vbuild/RHEL7-x86_64/python/3.8.5/lib/python3.8/doctest.py", line 104, in <module>
    import unittest
  File "/app/vbuild/RHEL7-x86_64/python/3.8.5/lib/python3.8/unittest/__init__.py", line 60, in <module>
    from .async_case import IsolatedAsyncioTestCase
  File "/app/vbuild/RHEL7-x86_64/python/3.8.5/lib/python3.8/unittest/async_case.py", line 1, in <module>
    import asyncio
  File "/app/vbuild/RHEL7-x86_64/python/3.8.5/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/app/vbuild/RHEL7-x86_64/python/3.8.5/lib/python3.8/asyncio/base_events.py", line 45, in <module>
    from . import staggered
  File "/app/vbuild/RHEL7-x86_64/python/3.8.5/lib/python3.8/asyncio/staggered.py", line 15, in <module>
    coro_fns: typing.Iterable[typing.Callable[[], typing.Awaitable]],
AttributeError: module 'typing' has no attribute 'Awaitable'

**Comment by zcold** [comment]
2.2.0 solves the problem
